import INF_LEDGER_HAS_BEEN_REMOVED from '@salesforce/label/c.INF_LEDGER_HAS_BEEN_REMOVED';
import INF_LEDGER_AND_CHILD_ELIMINATIONS from '@salesforce/label/c.INF_LEDGER_AND_CHILD_ELIMINATIONS';
import INF_HAVE_BEEN_REMOVED from '@salesforce/label/c.INF_HAVE_BEEN_REMOVED';
import WRN_ARE_YOU_SURE_TO_REMOVE from '@salesforce/label/c.WRN_ARE_YOU_SURE_TO_REMOVE';
import INF_REMOVING_LEDGER_DELETE_ELIMINATED_LEDGER_FINANCIAL_CUBES from '@salesforce/label/c.INF_REMOVING_LEDGER_DELETE_ELIMINATED_LEDGER_FINANCIAL_CUBES';

export default {
    INF_LEDGER_HAS_BEEN_REMOVED: INF_LEDGER_HAS_BEEN_REMOVED,
    INF_LEDGER_AND_CHILD_ELIMINATIONS: INF_LEDGER_AND_CHILD_ELIMINATIONS,
    INF_HAVE_BEEN_REMOVED: INF_HAVE_BEEN_REMOVED,
    WRN_ARE_YOU_SURE_TO_REMOVE: WRN_ARE_YOU_SURE_TO_REMOVE,
    INF_REMOVING_LEDGER_DELETE_ELIMINATED_LEDGER_FINANCIAL_CUBES: INF_REMOVING_LEDGER_DELETE_ELIMINATED_LEDGER_FINANCIAL_CUBES
}