import ERR_INITIAL_START_DATE_TOO_GREAT from '@salesforce/label/c.ERR_INITIAL_START_DATE_TOO_GREAT';
import INF_FINANCIAL_INSTITUTION_DELETED from '@salesforce/label/c.INF_FINANCIAL_INSTITUTION_DELETED';
import INF_DELETE_SUCCESSFUL from '@salesforce/label/c.INF_DELETE_SUCCESSFUL';
import ERR_DURING_DELETE from '@salesforce/label/c.ERR_DURING_DELETE';
import ERR_ON_THE_PAGE_RESOLVE from '@salesforce/label/c.ERR_ON_THE_PAGE_RESOLVE';
import INF_ACCOUNT_NAME from '@salesforce/label/c.INF_ACCOUNT_NAME';
import INF_INITIAL_START_DATE from '@salesforce/label/c.INF_INITIAL_START_DATE';
import INF_FIA_STATUS from '@salesforce/label/c.INF_FIA_STATUS';
import INF_PLAID from '@salesforce/label/c.INF_PLAID';
import INF_YODLEE from '@salesforce/label/c.INF_YODLEE';
import bdcPROVIDER from '@salesforce/label/c.BDC_PROVIDER';
import INF_REGISTER_PROVIDER from '@salesforce/label/c.INF_REGISTER_PROVIDER';
import INF_DEREGISTER_PROVIDER from '@salesforce/label/c.INF_DEREGISTER_PROVIDER';
import INF_DELETE_FINANCIAL_INSTITUTION from '@salesforce/label/c.INF_DELETE_FINANCIAL_INSTITUTION';
import INF_CHANGES_DETECTED from '@salesforce/label/c.INF_CHANGES_DETECTED';
import INF_FINANCIAL_INSTITUTIONS from '@salesforce/label/c.INF_FINANCIAL_INSTITUTIONS';
import INF_MANAGE_AGGREGATION_PROVIDERS from '@salesforce/label/c.INF_MANAGE_AGGREGATION_PROVIDERS';
import INF_REGISTER_DEREGISTER_WITH_PROVIDER from '@salesforce/label/c.INF_REGISTER_DEREGISTER_WITH_PROVIDER';
import INF_MANAGE_PROVIDERS from '@salesforce/label/c.INF_MANAGE_PROVIDERS';
import INF_SELECT_PROVIDER_AND_CONNECT_FINANCIAL_INSTITUTIONS from '@salesforce/label/c.INF_SELECT_PROVIDER_AND_CONNECT_FINANCIAL_INSTITUTIONS';
import INF_SELECT_AGGREGATION_PROVIDER from '@salesforce/label/c.INF_SELECT_AGGREGATION_PROVIDER';
import INF_SELECT_IDENTITY from '@salesforce/label/c.INF_SELECT_IDENTITY';
import INF_AGGREGATION_SERVICE_PROVIDER_FINANCIAL_INSTITUTION_PICKLIST from '@salesforce/label/c.INF_AGGREGATION_SERVICE_PROVIDER_FINANCIAL_INSTITUTION_PICKLIST';
import INF_SELECT_FINANCIAL_INSTITUTION from '@salesforce/label/c.INF_SELECT_FINANCIAL_INSTITUTION';
import INF_MAP_FINANCIAL_INSTITUTION_TO_GL_ACCOUNTS from '@salesforce/label/c.INF_MAP_FINANCIAL_INSTITUTION_TO_GL_ACCOUNTS';
import INF_FINANCIAL_INSTITUTIONS_FOR_SERVICE_PROVIDER from '@salesforce/label/c.INF_FINANCIAL_INSTITUTIONS_FOR_SERVICE_PROVIDER';
import INF_IDENTITY_SELECT_HELP from '@salesforce/label/c.INF_IDENTITY_SELECT_HELP';
import INF_ADD_SETTINGS from '@salesforce/label/c.INF_ADD_SETTINGS';
import INF_ENABLE_GLOBAL_AUTOMATED_ADD from '@salesforce/label/c.INF_ENABLE_GLOBAL_AUTOMATED_ADD';
import INF_CASH_IN_DEFAULT_SOURCE_RECORD_TYPE from '@salesforce/label/c.INF_CASH_IN_DEFAULT_SOURCE_RECORD_TYPE';
import INF_CASH_OUT_DEFAULT_SOURCE_RECORD_TYPE from '@salesforce/label/c.INF_CASH_OUT_DEFAULT_SOURCE_RECORD_TYPE';
import INF_PRE_POPULATED_ACCT_INFORMATION from '@salesforce/label/c.INF_PRE_POPULATED_ACCT_INFORMATION';
import INF_PRE_POPULATE_ACCT_INFO from '@salesforce/label/c.INF_PRE_POPULATE_ACCT_INFO';
import INF_MATCH_SETTINGS from '@salesforce/label/c.INF_MATCH_SETTINGS';
import bdcCashInMatchingSetting from '@salesforce/label/c.BDC_CASH_IN_MATCHING_SETTING';
import INF_DAYS from '@salesforce/label/c.INF_DAYS';
import INF_CASH_OUT_DEFAULT_MATCH_SETTING from '@salesforce/label/c.INF_CASH_OUT_DEFAULT_MATCH_SETTING';
import INF_SETTING_CHECKED_CANNOT_MAP_MORE_FIA_TO_BANK_ACCOUNT from '@salesforce/label/c.INF_SETTING_CHECKED_CANNOT_MAP_MORE_FIA_TO_BANK_ACCOUNT';
import INF_ENABLE_GLOBAL_AUTOMATED_MATCH from '@salesforce/label/c.INF_ENABLE_GLOBAL_AUTOMATED_MATCH';
import INF_SINGLE_FIA_PER_BANK_ACCOUNT from '@salesforce/label/c.INF_SINGLE_FIA_PER_BANK_ACCOUNT';
import INF_RELOAD_PAGE from '@salesforce/label/c.INF_RELOAD_PAGE';
import INF_CONFIRM_MANAGE_AGGREGATION_PROVIDERS from '@salesforce/label/c.INF_CONFIRM_MANAGE_AGGREGATION_PROVIDERS';
import bdcCountry from '@salesforce/label/c.COMMON_COUNTRY';
import bdcInfoCountryHelptext from '@salesforce/label/c.INFO_MULTI_SELECT_COUNTRY_PICKLIST';
import INF_CANADA from '@salesforce/label/c.INF_CANADA';
import INF_DENMARK from '@salesforce/label/c.INF_DENMARK';
import INF_FRANCE from '@salesforce/label/c.INF_FRANCE';
import INF_GERMANY from '@salesforce/label/c.INF_GERMANY';
import INF_IRELAND from '@salesforce/label/c.INF_IRELAND';
import INF_Netherlands from '@salesforce/label/c.INF_Netherlands';
import INF_PORTUGAL from '@salesforce/label/c.INF_PORTUGAL';
import INF_SPAIN from '@salesforce/label/c.INF_SPAIN';
import INF_SWEDEN from '@salesforce/label/c.INF_SWEDEN';
import INF_USA from '@salesforce/label/c.INF_USA';

export default {
    ERR_INITIAL_START_DATE_TOO_GREAT: ERR_INITIAL_START_DATE_TOO_GREAT,
    INF_FINANCIAL_INSTITUTION_DELETED: INF_FINANCIAL_INSTITUTION_DELETED,
    INF_DELETE_SUCCESSFUL: INF_DELETE_SUCCESSFUL,
    ERR_DURING_DELETE: ERR_DURING_DELETE,
    ERR_ON_THE_PAGE_RESOLVE: ERR_ON_THE_PAGE_RESOLVE,
    INF_ACCOUNT_NAME: INF_ACCOUNT_NAME,
    INF_INITIAL_START_DATE: INF_INITIAL_START_DATE,
    INF_FIA_STATUS: INF_FIA_STATUS,
    INF_PLAID: INF_PLAID,
    INF_YODLEE: INF_YODLEE,
    bdcPROVIDER: bdcPROVIDER,
    INF_REGISTER_PROVIDER: INF_REGISTER_PROVIDER,
    INF_DEREGISTER_PROVIDER: INF_DEREGISTER_PROVIDER,
    INF_DELETE_FINANCIAL_INSTITUTION: INF_DELETE_FINANCIAL_INSTITUTION,
    INF_CHANGES_DETECTED: INF_CHANGES_DETECTED,
    INF_FINANCIAL_INSTITUTIONS: INF_FINANCIAL_INSTITUTIONS,
    INF_MANAGE_AGGREGATION_PROVIDERS: INF_MANAGE_AGGREGATION_PROVIDERS,
    INF_REGISTER_DEREGISTER_WITH_PROVIDER: INF_REGISTER_DEREGISTER_WITH_PROVIDER,
    INF_MANAGE_PROVIDERS: INF_MANAGE_PROVIDERS,
    INF_SELECT_PROVIDER_AND_CONNECT_FINANCIAL_INSTITUTIONS: INF_SELECT_PROVIDER_AND_CONNECT_FINANCIAL_INSTITUTIONS,
    INF_SELECT_AGGREGATION_PROVIDER: INF_SELECT_AGGREGATION_PROVIDER,
    INF_SELECT_IDENTITY: INF_SELECT_IDENTITY,
    INF_AGGREGATION_SERVICE_PROVIDER_FINANCIAL_INSTITUTION_PICKLIST: INF_AGGREGATION_SERVICE_PROVIDER_FINANCIAL_INSTITUTION_PICKLIST,
    INF_SELECT_FINANCIAL_INSTITUTION: INF_SELECT_FINANCIAL_INSTITUTION,
    INF_FINANCIAL_INSTITUTIONS_FOR_SERVICE_PROVIDER: INF_FINANCIAL_INSTITUTIONS_FOR_SERVICE_PROVIDER,
    INF_IDENTITY_SELECT_HELP: INF_IDENTITY_SELECT_HELP,
    INF_MAP_FINANCIAL_INSTITUTION_TO_GL_ACCOUNTS: INF_MAP_FINANCIAL_INSTITUTION_TO_GL_ACCOUNTS,
    INF_SINGLE_FIA_PER_BANK_ACCOUNT: INF_SINGLE_FIA_PER_BANK_ACCOUNT,
    INF_SETTING_CHECKED_CANNOT_MAP_MORE_FIA_TO_BANK_ACCOUNT: INF_SETTING_CHECKED_CANNOT_MAP_MORE_FIA_TO_BANK_ACCOUNT,
    INF_ADD_SETTINGS: INF_ADD_SETTINGS,
    INF_ENABLE_GLOBAL_AUTOMATED_ADD: INF_ENABLE_GLOBAL_AUTOMATED_ADD,
    INF_CASH_IN_DEFAULT_SOURCE_RECORD_TYPE: INF_CASH_IN_DEFAULT_SOURCE_RECORD_TYPE,
    INF_CASH_OUT_DEFAULT_SOURCE_RECORD_TYPE: INF_CASH_OUT_DEFAULT_SOURCE_RECORD_TYPE,
    INF_PRE_POPULATED_ACCT_INFORMATION: INF_PRE_POPULATED_ACCT_INFORMATION,
    INF_PRE_POPULATE_ACCT_INFO: INF_PRE_POPULATE_ACCT_INFO,
    INF_MATCH_SETTINGS: INF_MATCH_SETTINGS,
    INF_ENABLE_GLOBAL_AUTOMATED_MATCH: INF_ENABLE_GLOBAL_AUTOMATED_MATCH,
    bdcCashInMatchingSetting: bdcCashInMatchingSetting,
    INF_DAYS: INF_DAYS,
    INF_CASH_OUT_DEFAULT_MATCH_SETTING: INF_CASH_OUT_DEFAULT_MATCH_SETTING,
    INF_RELOAD_PAGE: INF_RELOAD_PAGE,
    INF_CONFIRM_MANAGE_AGGREGATION_PROVIDERS: INF_CONFIRM_MANAGE_AGGREGATION_PROVIDERS,
    bdcCountry: bdcCountry,
    bdcInfoCountryHelptext: bdcInfoCountryHelptext,
    INF_CANADA: INF_CANADA,
    INF_DENMARK: INF_DENMARK,
    INF_FRANCE: INF_FRANCE,
    INF_GERMANY: INF_GERMANY,
    INF_IRELAND: INF_IRELAND,
    INF_Netherlands: INF_Netherlands,
    INF_PORTUGAL: INF_PORTUGAL,
    INF_SPAIN: INF_SPAIN,
    INF_SWEDEN: INF_SWEDEN,
    INF_USA: INF_USA
}