import INF_ENTER_1099_INFORMATION from '@salesforce/label/c.INF_ENTER_1099_INFORMATION';
import COMMON_RECORDS_SELECTED from '@salesforce/label/c.COMMON_RECORDS_SELECTED';
export default {
    INF_ENTER_1099_INFORMATION : INF_ENTER_1099_INFORMATION,
    COMMON_RECORDS_SELECTED : COMMON_RECORDS_SELECTED
}