import ERR_BALANCE_CAPS from '@salesforce/label/c.ERR_BALANCE_CAPS';
import ERR_TOTAL_CREDITS_MUST_EQUAL_TOTAL_DEBITS from '@salesforce/label/c.ERR_TOTAL_CREDITS_MUST_EQUAL_TOTAL_DEBITS';
import COMMON_NOT_VALID from '@salesforce/label/c.COMMON_NOT_VALID';
import IMPORT_PAYROLL_DATA_TABLE_SEARCH_TITLE from '@salesforce/label/c.IMPORT_PAYROLL_DATA_TABLE_SEARCH_TITLE';
import IMPORT_PAYROLL_FILE_JE_RECORD_ALREADY_EXISTS_MESSAGE from '@salesforce/label/c.IMPORT_PAYROLL_FILE_JE_RECORD_ALREADY_EXISTS_MESSAGE';
import COMMON_CREATED from '@salesforce/label/c.COMMON_CREATED';
import COMMON_ALREADY_EXISTS from '@salesforce/label/c.COMMON_ALREADY_EXISTS';
import COMMON_SHOWING from '@salesforce/label/c.COMMON_SHOWING';
import COMMON_TO from '@salesforce/label/c.COMMON_TO';
import COMMON_OF from '@salesforce/label/c.COMMON_OF';
import COMMON_ENTRIES from '@salesforce/label/c.COMMON_ENTRIES';
export default {
    ERR_BALANCE_CAPS : ERR_BALANCE_CAPS,
    ERR_TOTAL_CREDITS_MUST_EQUAL_TOTAL_DEBITS : ERR_TOTAL_CREDITS_MUST_EQUAL_TOTAL_DEBITS,
    COMMON_NOT_VALID : COMMON_NOT_VALID,
    IMPORT_PAYROLL_DATA_TABLE_SEARCH_TITLE : IMPORT_PAYROLL_DATA_TABLE_SEARCH_TITLE,
    IMPORT_PAYROLL_FILE_JE_RECORD_ALREADY_EXISTS_MESSAGE : IMPORT_PAYROLL_FILE_JE_RECORD_ALREADY_EXISTS_MESSAGE,
    COMMON_ALREADY_EXISTS : COMMON_ALREADY_EXISTS,
    COMMON_CREATED : COMMON_CREATED,
    COMMON_SHOWING : COMMON_SHOWING,
    COMMON_TO : COMMON_TO,
    COMMON_OF : COMMON_OF,
    COMMON_ENTRIES : COMMON_ENTRIES
}