import INF_CHANGE_SETTINGS from '@salesforce/label/c.INF_CHANGE_SETTINGS';
import INF_IMPORT_COMPLETE from '@salesforce/label/c.INF_IMPORT_COMPLETE';
import INF_FINANCIAL_FILE_IMPORT_UTILITIES_SUPPORT from '@salesforce/label/c.INF_FINANCIAL_FILE_IMPORT_UTILITIES_SUPPORT';

export default {
    INF_CHANGE_SETTINGS: INF_CHANGE_SETTINGS,
    INF_IMPORT_COMPLETE: INF_IMPORT_COMPLETE,
    INF_FINANCIAL_FILE_IMPORT_UTILITIES_SUPPORT: INF_FINANCIAL_FILE_IMPORT_UTILITIES_SUPPORT
}