import ACCOUNTING_SEED_COPILOT from '@salesforce/label/c.ACCOUNTING_SEED_COPILOT';
import ERR_ACCOUNTING_SEED_COPILOT_LOAD from '@salesforce/label/c.ERR_ACCOUNTING_SEED_COPILOT_LOAD';
export default {
    ACCOUNTING_SEED_COPILOT: ACCOUNTING_SEED_COPILOT,
    ERR_ACCOUNTING_SEED_COPILOT_LOAD: ERR_ACCOUNTING_SEED_COPILOT_LOAD
}