import ERR_BALANCE_AGGREGATION from '@salesforce/label/c.ERR_BALANCE_AGGREGATION';
import INF_FEATURE_FOR_BALANCE_SHEET_REVENUE_EXPENSE_TYPE_GL_ACCTS from '@salesforce/label/c.INF_FEATURE_FOR_BALANCE_SHEET_REVENUE_EXPENSE_TYPE_GL_ACCTS';

export default {
    ERR_BALANCE_AGGREGATION: ERR_BALANCE_AGGREGATION,
    INF_FEATURE_FOR_BALANCE_SHEET_REVENUE_EXPENSE_TYPE_GL_ACCTS: INF_FEATURE_FOR_BALANCE_SHEET_REVENUE_EXPENSE_TYPE_GL_ACCTS,

}