import INF_DESCRIPTION_OF_ITEM_NEEDED from '@salesforce/label/c.INF_DESCRIPTION_OF_ITEM_NEEDED';
import INF_SHOW_DETAILS from '@salesforce/label/c.INF_SHOW_DETAILS';
import ERR_RETRIEVING_DATA from '@salesforce/label/c.ERR_RETRIEVING_DATA';

export default {
    INF_DESCRIPTION_OF_ITEM_NEEDED: INF_DESCRIPTION_OF_ITEM_NEEDED,
    INF_SHOW_DETAILS: INF_SHOW_DETAILS,
    ERR_RETRIEVING_DATA: ERR_RETRIEVING_DATA
}