import INF_TRANSACTIONAL_LEDGER from '@salesforce/label/c.INF_TRANSACTIONAL_LEDGER';
import INF_BUDGET_LEDGER_FOR_REPORT from '@salesforce/label/c.INF_BUDGET_LEDGER_FOR_REPORT';

export default {
    INF_TRANSACTIONAL_LEDGER: INF_TRANSACTIONAL_LEDGER,
    INF_BUDGET_LEDGER_FOR_REPORT: INF_BUDGET_LEDGER_FOR_REPORT,
}