//import accountingHomeBDC from '@salesforce/label/c.ACCOUNTING_HOME_BDC';
import INF_UPDATE_ALL from '@salesforce/label/c.INF_UPDATE_ALL';
import INF_IMPORT_FILE from '@salesforce/label/c.INF_IMPORT_FILE';
import INF_IMPORT_OFX_QFX_FINANCIAL_FILE from '@salesforce/label/c.INF_IMPORT_OFX_QFX_FINANCIAL_FILE';
import INF_BANK_TRANSACTIONS from '@salesforce/label/c.INF_BANK_TRANSACTIONS';
import INF_BANK_RULES from '@salesforce/label/c.INF_BANK_RULES';
import INF_NO_ACCESS_ASSIGN_PERMISSION_IMPORT_BDC_TRNS from '@salesforce/label/c.INF_NO_ACCESS_ASSIGN_PERMISSION_IMPORT_BDC_TRNS';
import INF_FINANCIAL_FILE_IMPORT from '@salesforce/label/c.INF_FINANCIAL_FILE_IMPORT';
import INF_BANK_UPDATE_IN_PROGRESS_ASYNC from '@salesforce/label/c.INF_BANK_UPDATE_IN_PROGRESS_ASYNC';
import INF_BANK_UPDATE_RUNNING from '@salesforce/label/c.INF_BANK_UPDATE_RUNNING';
import INF_PLEASE_REFRESH_PAGE from '@salesforce/label/c.INF_PLEASE_REFRESH_PAGE';
import INF_BANK_UPDATE_FAILED from '@salesforce/label/c.INF_BANK_UPDATE_FAILED';

export default {
    //accountingHomeBDC: accountingHomeBDC,
    INF_UPDATE_ALL: INF_UPDATE_ALL,
    INF_IMPORT_FILE: INF_IMPORT_FILE,
    INF_IMPORT_OFX_QFX_FINANCIAL_FILE: INF_IMPORT_OFX_QFX_FINANCIAL_FILE,
    INF_BANK_TRANSACTIONS: INF_BANK_TRANSACTIONS,
    INF_BANK_RULES: INF_BANK_RULES,
    INF_NO_ACCESS_ASSIGN_PERMISSION_IMPORT_BDC_TRNS: INF_NO_ACCESS_ASSIGN_PERMISSION_IMPORT_BDC_TRNS,
    INF_FINANCIAL_FILE_IMPORT: INF_FINANCIAL_FILE_IMPORT,
    INF_BANK_UPDATE_IN_PROGRESS_ASYNC: INF_BANK_UPDATE_IN_PROGRESS_ASYNC,
    INF_BANK_UPDATE_RUNNING: INF_BANK_UPDATE_RUNNING,
    INF_PLEASE_REFRESH_PAGE: INF_PLEASE_REFRESH_PAGE,
    INF_BANK_UPDATE_FAILED: INF_BANK_UPDATE_FAILED
}