import ERR_CR_BALANCE_CANNOT_LESS_THAN_0 from '@salesforce/label/c.ERR_CR_BALANCE_CANNOT_LESS_THAN_0';
import ERR_RECIEVED_AMT_CANNOT_LESS_THAN_0 from '@salesforce/label/c.ERR_RECIEVED_AMT_CANNOT_LESS_THAN_0';
import ERR_LOADING_ASSOCIATED_INVOICES from '@salesforce/label/c.ERR_LOADING_ASSOCIATED_INVOICES';
import ERR_LOADING_CASH_RECEIPT from '@salesforce/label/c.ERR_LOADING_CASH_RECEIPT';
import ERR_ADJUSTMENT_GL_ACCT_REQ from '@salesforce/label/c.ERR_ADJUSTMENT_GL_ACCT_REQ';
import ERR_CR_MODIFIED_REFRESH from '@salesforce/label/c.ERR_CR_MODIFIED_REFRESH';
import INF_ADJUSTMENT_AMT from '@salesforce/label/c.INF_ADJUSTMENT_AMT';
import INF_RECEIPT_DATE from '@salesforce/label/c.INF_RECEIPT_DATE';
import ERR_PLEASE_CORRECT_ERROR_FOR_BILLING from '@salesforce/label/c.ERR_PLEASE_CORRECT_ERROR_FOR_BILLING';
import ERR_ADJUSTMENT_AMT_CANNOT_LESS_THAN_0 from '@salesforce/label/c.ERR_ADJUSTMENT_AMT_CANNOT_LESS_THAN_0';

export default {
    ERR_CR_BALANCE_CANNOT_LESS_THAN_0: ERR_CR_BALANCE_CANNOT_LESS_THAN_0,
    ERR_RECIEVED_AMT_CANNOT_LESS_THAN_0: ERR_RECIEVED_AMT_CANNOT_LESS_THAN_0,
    ERR_LOADING_ASSOCIATED_INVOICES: ERR_LOADING_ASSOCIATED_INVOICES,
    ERR_LOADING_CASH_RECEIPT: ERR_LOADING_CASH_RECEIPT,
    ERR_ADJUSTMENT_GL_ACCT_REQ: ERR_ADJUSTMENT_GL_ACCT_REQ,
    ERR_CR_MODIFIED_REFRESH: ERR_CR_MODIFIED_REFRESH,
    INF_ADJUSTMENT_AMT: INF_ADJUSTMENT_AMT,
    INF_RECEIPT_DATE: INF_RECEIPT_DATE,
    ERR_PLEASE_CORRECT_ERROR_FOR_BILLING: ERR_PLEASE_CORRECT_ERROR_FOR_BILLING,
    ERR_ADJUSTMENT_AMT_CANNOT_LESS_THAN_0: ERR_ADJUSTMENT_AMT_CANNOT_LESS_THAN_0
}