import INF_EXPAND_OR_COLLAPSE from '@salesforce/label/c.INF_EXPAND_OR_COLLAPSE';
import INF_MENU_LOWERCASE from '@salesforce/label/c.INF_MENU_LOWERCASE';

export default {
    INF_EXPAND_OR_COLLAPSE: INF_EXPAND_OR_COLLAPSE,
    INF_MENU_LOWERCASE: INF_MENU_LOWERCASE
}