import WRN_CHANGING_SOURCE_TYPE_REMOVE_REMAINING_ACTIONS from '@salesforce/label/c.WRN_CHANGING_SOURCE_TYPE_REMOVE_REMAINING_ACTIONS';
import INF_PROCEED from '@salesforce/label/c.INF_PROCEED';
import INF_FINANCIAL_INSTITUTION_ACCOUNTS from '@salesforce/label/c.INF_FINANCIAL_INSTITUTION_ACCOUNTS';
import INF_FIA_APPLIES_TO_BANK_RULE from '@salesforce/label/c.INF_FIA_APPLIES_TO_BANK_RULE';
import INF_SELECT_ALL_FIAS from '@salesforce/label/c.INF_SELECT_ALL_FIAS';
import INF_AVAILAIBLE from '@salesforce/label/c.INF_AVAILAIBLE';
import INF_CONDITIONS from '@salesforce/label/c.INF_CONDITIONS';
import INF_IF from '@salesforce/label/c.INF_IF';
import INF_OF_FOLLOWING_CONDITIONS_MET from '@salesforce/label/c.INF_OF_FOLLOWING_CONDITIONS_MET';
import INF_BANK_RULES_PROCESSES_CONDITION from '@salesforce/label/c.INF_BANK_RULES_PROCESSES_CONDITION';
import INF_SET_THE_RECORD_TYPE from '@salesforce/label/c.INF_SET_THE_RECORD_TYPE';

export default {
    WRN_CHANGING_SOURCE_TYPE_REMOVE_REMAINING_ACTIONS: WRN_CHANGING_SOURCE_TYPE_REMOVE_REMAINING_ACTIONS,
    INF_PROCEED: INF_PROCEED,
    INF_FINANCIAL_INSTITUTION_ACCOUNTS: INF_FINANCIAL_INSTITUTION_ACCOUNTS,
    INF_FIA_APPLIES_TO_BANK_RULE: INF_FIA_APPLIES_TO_BANK_RULE,
    INF_SELECT_ALL_FIAS: INF_SELECT_ALL_FIAS,
    INF_AVAILAIBLE: INF_AVAILAIBLE,
    INF_CONDITIONS: INF_CONDITIONS,
    INF_IF: INF_IF,
    INF_OF_FOLLOWING_CONDITIONS_MET: INF_OF_FOLLOWING_CONDITIONS_MET,
    INF_BANK_RULES_PROCESSES_CONDITION: INF_BANK_RULES_PROCESSES_CONDITION,
    INF_SET_THE_RECORD_TYPE: INF_SET_THE_RECORD_TYPE
}