import COMMON_WARNING from '@salesforce/label/c.COMMON_WARNING';
import INF_LAST_CLOSED_PERIOD_DATE_30_MORE_THAN_TODAY from '@salesforce/label/c.INF_LAST_CLOSED_PERIOD_DATE_30_MORE_THAN_TODAY';
export default {
    COMMON_WARNING : COMMON_WARNING,
    INF_LAST_CLOSED_PERIOD_DATE_30_MORE_THAN_TODAY : INF_LAST_CLOSED_PERIOD_DATE_30_MORE_THAN_TODAY
}