import INF_ADD_COMMENTS from '@salesforce/label/c.INF_ADD_COMMENTS';
import INF_VIEW_COMMENTS from '@salesforce/label/c.INF_VIEW_COMMENTS';
import COMMON_INTERNAL_COMMENT from '@salesforce/label/c.COMMON_INTERNAL_COMMENT';
import INF_INVOICE_COMMENT from '@salesforce/label/c.INF_INVOICE_COMMENT';
import INF_INSUFFICIENT_PRIVILIGES from '@salesforce/label/c.INF_INSUFFICIENT_PRIVILIGES';
import INF_NOT_ACCESS_PERFORM_OPERATION from '@salesforce/label/c.INF_NOT_ACCESS_PERFORM_OPERATION';

export default {
    INF_ADD_COMMENTS: INF_ADD_COMMENTS,
    INF_VIEW_COMMENTS: INF_VIEW_COMMENTS,
    COMMON_INTERNAL_COMMENT: COMMON_INTERNAL_COMMENT,
    INF_INVOICE_COMMENT: INF_INVOICE_COMMENT,
    INF_INSUFFICIENT_PRIVILIGES: INF_INSUFFICIENT_PRIVILIGES,
    INF_NOT_ACCESS_PERFORM_OPERATION: INF_NOT_ACCESS_PERFORM_OPERATION
}