import ERR_TIME_CARD_LINES_UPDATE_NOT_COMPLETED from '@salesforce/label/c.ERR_TIME_CARD_LINES_UPDATE_NOT_COMPLETED';
import ERR_CANNOT_EDIT_POSTED_TIME_CARD from '@salesforce/label/c.ERR_CANNOT_EDIT_POSTED_TIME_CARD';
import ERR_NO_TIME_CARD_LINES_EXIST_CLICK_ADD_NEW from '@salesforce/label/c.ERR_NO_TIME_CARD_LINES_EXIST_CLICK_ADD_NEW';
import INF_DELETE_TIME_CARD_LINE from '@salesforce/label/c.INF_DELETE_TIME_CARD_LINE';
import INF_ARE_YOU_SURE_DELETE_TIME_CARD_LINE from '@salesforce/label/c.INF_ARE_YOU_SURE_DELETE_TIME_CARD_LINE';
export default {
    ERR_TIME_CARD_LINES_UPDATE_NOT_COMPLETED : ERR_TIME_CARD_LINES_UPDATE_NOT_COMPLETED,
    ERR_CANNOT_EDIT_POSTED_TIME_CARD : ERR_CANNOT_EDIT_POSTED_TIME_CARD,
    ERR_NO_TIME_CARD_LINES_EXIST_CLICK_ADD_NEW : ERR_NO_TIME_CARD_LINES_EXIST_CLICK_ADD_NEW,
    INF_DELETE_TIME_CARD_LINE : INF_DELETE_TIME_CARD_LINE,
    INF_ARE_YOU_SURE_DELETE_TIME_CARD_LINE : INF_ARE_YOU_SURE_DELETE_TIME_CARD_LINE
}