import INF_CASH_OUT_DEFAULT_MATCH_SETTING from '@salesforce/label/c.INF_CASH_OUT_DEFAULT_MATCH_SETTING';
import INF_FIA_CURRENCY from '@salesforce/label/c.INF_FIA_CURRENCY';
import INF_FIA_CREDENTIALS_MFA_NEED_REFRESH_LAST_UPDATE_WITH_BANK_ACCT from '@salesforce/label/c.INF_FIA_CREDENTIALS_MFA_NEED_REFRESH_LAST_UPDATE_WITH_BANK_ACCT';
import INF_AVAILAIBLE_BALANCE from '@salesforce/label/c.INF_AVAILAIBLE_BALANCE';
import INF_YOUR_RECORDS_CREATED from '@salesforce/label/c.INF_YOUR_RECORDS_CREATED';
import INF_CREATE_SUCCESSFUL from '@salesforce/label/c.INF_CREATE_SUCCESSFUL';
import INF_BANK_TRX_NAME from '@salesforce/label/c.INF_BANK_TRX_NAME';
import INF_HIGH_LEVEL_CATEGORY from '@salesforce/label/c.INF_HIGH_LEVEL_CATEGORY';
import INF_DETAIL_CATEGORY from '@salesforce/label/c.INF_DETAIL_CATEGORY';
import INF_MASTER_CATEGORY from '@salesforce/label/c.INF_MASTER_CATEGORY';
import INF_SOURCE_LINK from '@salesforce/label/c.INF_SOURCE_LINK';
import INF_BANK_ID from '@salesforce/label/c.INF_BANK_ID';
import INF_ALL_BANK_TRANSACTIONS from '@salesforce/label/c.INF_ALL_BANK_TRANSACTIONS';
import INF_UNMATCHED_BANK_TRANSACTIONS from '@salesforce/label/c.INF_UNMATCHED_BANK_TRANSACTIONS';
import WRN_ACCOUNT_NOT_UPDATE_GO_TO_BANK_SETTINGS from '@salesforce/label/c.WRN_ACCOUNT_NOT_UPDATE_GO_TO_BANK_SETTINGS';
import WRN_FIA_FAILED_TO_CONNECT from '@salesforce/label/c.WRN_FIA_FAILED_TO_CONNECT';
import INF_FINANCIAL_INSTITUTION_ACCOUNT from '@salesforce/label/c.INF_FINANCIAL_INSTITUTION_ACCOUNT';
import INF_RECENT_RECORDS_DISPLAYED from '@salesforce/label/c.INF_RECENT_RECORDS_DISPLAYED';
import INF_BANK_CREDIT_CARD_TRXNS from '@salesforce/label/c.INF_BANK_CREDIT_CARD_TRXNS';
import INF_FILTER_BANK_TRANSACTIONS from '@salesforce/label/c.INF_FILTER_BANK_TRANSACTIONS';
import TRANSACTION_DOWNLOAD_PROGRESS from '@salesforce/label/c.TRANSACTION_DOWNLOAD_PROGRESS';
import BDC_DOWNLOAD_TRANSACTIONS from '@salesforce/label/c.BDC_DOWNLOAD_TRANSACTIONS';
import BDC_DOWNLOAD from '@salesforce/label/c.BDC_DOWNLOAD';
import BDC_TRANSACTION_MODAL_DOWNLOAD from '@salesforce/label/c.BDC_TRANSACTION_MODAL_DOWNLOAD';
import INF_PLAID from '@salesforce/label/c.INF_PLAID';

export default {
    INF_CASH_OUT_DEFAULT_MATCH_SETTING: INF_CASH_OUT_DEFAULT_MATCH_SETTING,
    INF_FIA_CURRENCY: INF_FIA_CURRENCY,
    INF_FIA_CREDENTIALS_MFA_NEED_REFRESH_LAST_UPDATE_WITH_BANK_ACCT: INF_FIA_CREDENTIALS_MFA_NEED_REFRESH_LAST_UPDATE_WITH_BANK_ACCT,
    INF_AVAILAIBLE_BALANCE: INF_AVAILAIBLE_BALANCE,
    INF_YOUR_RECORDS_CREATED: INF_YOUR_RECORDS_CREATED,
    INF_CREATE_SUCCESSFUL: INF_CREATE_SUCCESSFUL,
    INF_BANK_TRX_NAME: INF_BANK_TRX_NAME,
    INF_HIGH_LEVEL_CATEGORY: INF_HIGH_LEVEL_CATEGORY,
    INF_DETAIL_CATEGORY: INF_DETAIL_CATEGORY,
    INF_MASTER_CATEGORY: INF_MASTER_CATEGORY,
    INF_SOURCE_LINK: INF_SOURCE_LINK,
    INF_BANK_ID: INF_BANK_ID,
    INF_ALL_BANK_TRANSACTIONS: INF_ALL_BANK_TRANSACTIONS,
    INF_UNMATCHED_BANK_TRANSACTIONS: INF_UNMATCHED_BANK_TRANSACTIONS,
    WRN_ACCOUNT_NOT_UPDATE_GO_TO_BANK_SETTINGS: WRN_ACCOUNT_NOT_UPDATE_GO_TO_BANK_SETTINGS,
    WRN_FIA_FAILED_TO_CONNECT: WRN_FIA_FAILED_TO_CONNECT,
    INF_FINANCIAL_INSTITUTION_ACCOUNT: INF_FINANCIAL_INSTITUTION_ACCOUNT,
    INF_RECENT_RECORDS_DISPLAYED: INF_RECENT_RECORDS_DISPLAYED,
    INF_BANK_CREDIT_CARD_TRXNS: INF_BANK_CREDIT_CARD_TRXNS,
    INF_FILTER_BANK_TRANSACTIONS: INF_FILTER_BANK_TRANSACTIONS,
    TRANSACTION_DOWNLOAD_PROGRESS: TRANSACTION_DOWNLOAD_PROGRESS,
    BDC_DOWNLOAD_TRANSACTIONS: BDC_DOWNLOAD_TRANSACTIONS,
    BDC_DOWNLOAD: BDC_DOWNLOAD,
    BDC_TRANSACTION_MODAL_DOWNLOAD: BDC_TRANSACTION_MODAL_DOWNLOAD,
    INF_PLAID: INF_PLAID
}