import ERR_PAYABLE_IS_INVOICE_NOT_CREDIT_MEMO from '@salesforce/label/c.ERR_PAYABLE_IS_INVOICE_NOT_CREDIT_MEMO';
import COMMON_PAYABLE_AMOUNT from '@salesforce/label/c.COMMON_PAYABLE_AMOUNT';
import COMMON_TOTAL_APPLIED from '@salesforce/label/c.COMMON_TOTAL_APPLIED';
import COMMON_PAYABLE_BALANCE from '@salesforce/label/c.COMMON_PAYABLE_BALANCE';
import COMMON_APPLY from '@salesforce/label/c.COMMON_APPLY';
import COMMON_APPLIED_AMOUNT from '@salesforce/label/c.COMMON_APPLIED_AMOUNT';
import COMMON_APPLIED_DATE from '@salesforce/label/c.COMMON_APPLIED_DATE';
import COMMON_PAYEE from '@salesforce/label/c.COMMON_PAYEE';
import COMMON_ACCOUNTING_PERIOD from '@salesforce/label/c.COMMON_ACCOUNTING_PERIOD';
import X_DATA_SAVED_SUCCESSFULLY from '@salesforce/label/c.X_DATA_SAVED_SUCCESSFULLY';
import ERR_PLEASE_CORRECT_PAYABLE_ERRORS from '@salesforce/label/c.ERR_PLEASE_CORRECT_PAYABLE_ERRORS';
import COMMON_SEARCH_PAYABLES from '@salesforce/label/c.COMMON_SEARCH_PAYABLES';
import COMMON_UNSAVED_CHANGES from '@salesforce/label/c.COMMON_UNSAVED_CHANGES';
import COMMON_UNSAVED_CHANGES_DISCARD_CONTINUE from '@salesforce/label/c.COMMON_UNSAVED_CHANGES_DISCARD_CONTINUE';
import COMMON_PAYABLE from '@salesforce/label/c.COMMON_PAYABLE';
import ERR_CREDIT_MEMO_TO_A_PAYABLE_WITH_ON_HOLD from '@salesforce/label/c.ERR_CREDIT_MEMO_TO_A_PAYABLE_WITH_ON_HOLD';
export default {
    ERR_PAYABLE_IS_INVOICE_NOT_CREDIT_MEMO : ERR_PAYABLE_IS_INVOICE_NOT_CREDIT_MEMO,    
    COMMON_PAYABLE_AMOUNT : COMMON_PAYABLE_AMOUNT,
    COMMON_TOTAL_APPLIED : COMMON_TOTAL_APPLIED,
    COMMON_PAYABLE_BALANCE : COMMON_PAYABLE_BALANCE,
    COMMON_APPLY : COMMON_APPLY,
    COMMON_APPLIED_AMOUNT : COMMON_APPLIED_AMOUNT,
    COMMON_APPLIED_DATE : COMMON_APPLIED_DATE,
    COMMON_PAYEE : COMMON_PAYEE,
    COMMON_ACCOUNTING_PERIOD : COMMON_ACCOUNTING_PERIOD,
    X_DATA_SAVED_SUCCESSFULLY : X_DATA_SAVED_SUCCESSFULLY,
    ERR_PLEASE_CORRECT_PAYABLE_ERRORS : ERR_PLEASE_CORRECT_PAYABLE_ERRORS,
    COMMON_SEARCH_PAYABLES : COMMON_SEARCH_PAYABLES,
    COMMON_UNSAVED_CHANGES : COMMON_UNSAVED_CHANGES,
    COMMON_UNSAVED_CHANGES_DISCARD_CONTINUE : COMMON_UNSAVED_CHANGES_DISCARD_CONTINUE,
    COMMON_PAYABLE : COMMON_PAYABLE,
    ERR_CREDIT_MEMO_TO_A_PAYABLE_WITH_ON_HOLD : ERR_CREDIT_MEMO_TO_A_PAYABLE_WITH_ON_HOLD

}