import ERR_NO_REPORTS_TO_DELETE from '@salesforce/label/c.ERR_NO_REPORTS_TO_DELETE';
import INF_REPORT_GENERATION_COMPLETE from '@salesforce/label/c.INF_REPORT_GENERATION_COMPLETE';
import ERR_DELETING_REPORT from '@salesforce/label/c.ERR_DELETING_REPORT';
import INF_DELETE_REPORTS from '@salesforce/label/c.INF_DELETE_REPORTS';
import WRN_DELETING_REPORTS from '@salesforce/label/c.WRN_DELETING_REPORTS';
import INF_REPORTS from '@salesforce/label/c.INF_REPORTS';
import INF_REPORT_NUMBER from '@salesforce/label/c.INF_REPORT_NUMBER';
import INF_COMPLETED_DATE_OR_TIME from '@salesforce/label/c.INF_COMPLETED_DATE_OR_TIME';
import INF_REPORT_NAME_TEXT from '@salesforce/label/c.INF_REPORT_NAME_TEXT';

export default {
    ERR_NO_REPORTS_TO_DELETE: ERR_NO_REPORTS_TO_DELETE,
    INF_REPORT_GENERATION_COMPLETE: INF_REPORT_GENERATION_COMPLETE,
    ERR_DELETING_REPORT: ERR_DELETING_REPORT,
    INF_DELETE_REPORTS: INF_DELETE_REPORTS,
    WRN_DELETING_REPORTS: WRN_DELETING_REPORTS,
    INF_REPORTS: INF_REPORTS,
    INF_REPORT_NUMBER: INF_REPORT_NUMBER,
    INF_COMPLETED_DATE_OR_TIME: INF_COMPLETED_DATE_OR_TIME,
    INF_REPORT_NAME_TEXT: INF_REPORT_NAME_TEXT
}