import INF_FILTER_BY_PAYABLE_AMOUNT_MUST_FILTER_BY_DUE_OR_ISSUE_DATE from '@salesforce/label/c.INF_FILTER_BY_PAYABLE_AMOUNT_MUST_FILTER_BY_DUE_OR_ISSUE_DATE';
import COMMON_PAYEE_REFERENCE from '@salesforce/label/c.COMMON_PAYEE_REFERENCE';
import COMMON_ISSUE_DATE_RANGE from '@salesforce/label/c.COMMON_ISSUE_DATE_RANGE';
import COMMON_ISSUE_DATE_START from '@salesforce/label/c.COMMON_ISSUE_DATE_START';
import COMMON_ISSUE_DATE_END from '@salesforce/label/c.COMMON_ISSUE_DATE_END';
import COMMON_PAYABLE_AMOUNT from '@salesforce/label/c.COMMON_PAYABLE_AMOUNT';
export default {
    INF_FILTER_BY_PAYABLE_AMOUNT_MUST_FILTER_BY_DUE_OR_ISSUE_DATE : INF_FILTER_BY_PAYABLE_AMOUNT_MUST_FILTER_BY_DUE_OR_ISSUE_DATE,
    COMMON_PAYEE_REFERENCE : COMMON_PAYEE_REFERENCE,
    COMMON_ISSUE_DATE_RANGE : COMMON_ISSUE_DATE_RANGE,
    COMMON_ISSUE_DATE_START : COMMON_ISSUE_DATE_START,
    COMMON_ISSUE_DATE_END : COMMON_ISSUE_DATE_END,
    COMMON_PAYABLE_AMOUNT : COMMON_PAYABLE_AMOUNT
}