import INF_FILTER_PAYABLES from '@salesforce/label/c.INF_FILTER_PAYABLES';
import ERR_CASH_DISBURSEMENT_BALANCE_LESS_THAN_0 from '@salesforce/label/c.ERR_CASH_DISBURSEMENT_BALANCE_LESS_THAN_0';
import ERR_LOADING_ASSOCIATED_PAYABLES from '@salesforce/label/c.ERR_LOADING_ASSOCIATED_PAYABLES';
import ERR_LOADING_CASH_DISBURSEMENT from '@salesforce/label/c.ERR_LOADING_CASH_DISBURSEMENT';
import ERR_CD_LAST_MODIFIED from '@salesforce/label/c.ERR_CD_LAST_MODIFIED';
import INF_DISBURSEMENT_DATE from '@salesforce/label/c.INF_DISBURSEMENT_DATE';
import ERR_FOR_PAYABLES from '@salesforce/label/c.ERR_FOR_PAYABLES';
import ERR_CD_NOT_APPLIED_TO_PAYABLE_ON_HOLD from '@salesforce/label/c.ERR_CASH_DISBURSEMENT_CANNOT_BE_APPLIED_TO_A_PAYABLE_ON_HOLD';

export default {
    INF_FILTER_PAYABLES: INF_FILTER_PAYABLES,
    ERR_CASH_DISBURSEMENT_BALANCE_LESS_THAN_0: ERR_CASH_DISBURSEMENT_BALANCE_LESS_THAN_0,
    ERR_LOADING_ASSOCIATED_PAYABLES: ERR_LOADING_ASSOCIATED_PAYABLES,
    ERR_LOADING_CASH_DISBURSEMENT: ERR_LOADING_CASH_DISBURSEMENT,
    ERR_CD_LAST_MODIFIED: ERR_CD_LAST_MODIFIED,
    INF_DISBURSEMENT_DATE: INF_DISBURSEMENT_DATE,
    ERR_FOR_PAYABLES: ERR_FOR_PAYABLES,
    ERR_CD_NOT_APPLIED_TO_PAYABLE_ON_HOLD : ERR_CD_NOT_APPLIED_TO_PAYABLE_ON_HOLD
}