import INF_BILLING_CASH_RECEIPTS from '@salesforce/label/c.INF_BILLING_CASH_RECEIPTS';
import INF_INBOUND_ORDER_INVENTORY_MOVEMENTS from '@salesforce/label/c.INF_INBOUND_ORDER_INVENTORY_MOVEMENTS';
import INF_MANUFACTURING_INVENTORY_MOVEMENTS from '@salesforce/label/c.INF_MANUFACTURING_INVENTORY_MOVEMENTS';
import INF_OUTBOUND_INVENTORY_MOVEMENTS from '@salesforce/label/c.INF_OUTBOUND_INVENTORY_MOVEMENTS';
import INF_PURCHASE_ORDER_INVENTORY_MOVEMENTS from '@salesforce/label/c.INF_PURCHASE_ORDER_INVENTORY_MOVEMENTS';
import INF_SALES_ORDER_INVENTORY_MOVEMENTS from '@salesforce/label/c.INF_SALES_ORDER_INVENTORY_MOVEMENTS';
import INF_ADD_SCHEDULED_JOBS from '@salesforce/label/c.INF_ADD_SCHEDULED_JOBS';

export default {
    INF_BILLING_CASH_RECEIPTS: INF_BILLING_CASH_RECEIPTS,
    INF_INBOUND_ORDER_INVENTORY_MOVEMENTS: INF_INBOUND_ORDER_INVENTORY_MOVEMENTS,
    INF_MANUFACTURING_INVENTORY_MOVEMENTS: INF_MANUFACTURING_INVENTORY_MOVEMENTS,
    INF_OUTBOUND_INVENTORY_MOVEMENTS: INF_OUTBOUND_INVENTORY_MOVEMENTS,
    INF_PURCHASE_ORDER_INVENTORY_MOVEMENTS: INF_PURCHASE_ORDER_INVENTORY_MOVEMENTS,
    INF_SALES_ORDER_INVENTORY_MOVEMENTS: INF_SALES_ORDER_INVENTORY_MOVEMENTS,
    INF_ADD_SCHEDULED_JOBS: INF_ADD_SCHEDULED_JOBS,
}