import INF_ADDITIONAL_INFORMATION from '@salesforce/label/c.INF_ADDITIONAL_INFORMATION';
import INF_BANK_RECONCILIATION_INFORMATION from '@salesforce/label/c.INF_BANK_RECONCILIATION_INFORMATION';
import ERR_UPDATE_RECORD_TRY_AGAIN from '@salesforce/label/c.ERR_UPDATE_RECORD_TRY_AGAIN';
import INF_CREATE_NEXT_BANK_RECONCILIATION from '@salesforce/label/c.INF_CREATE_NEXT_BANK_RECONCILIATION';
import INF_BANK_RECONCILIATION_LIST_VIEW_KOALI_MAKE_NEW from '@salesforce/label/c.INF_BANK_RECONCILIATION_LIST_VIEW_KOALI_MAKE_NEW';
import INF_AUTO_POPULATE_FIELDS_BANK_RECONCILIATION from '@salesforce/label/c.INF_AUTO_POPULATE_FIELDS_BANK_RECONCILIATION';
import INF_DATE_BETWEEN_STMT_BANK_RECONCILIATION from '@salesforce/label/c.INF_DATE_BETWEEN_STMT_BANK_RECONCILIATION';

export default {
    INF_ADDITIONAL_INFORMATION: INF_ADDITIONAL_INFORMATION,
    INF_BANK_RECONCILIATION_INFORMATION: INF_BANK_RECONCILIATION_INFORMATION,
    ERR_UPDATE_RECORD_TRY_AGAIN: ERR_UPDATE_RECORD_TRY_AGAIN,
    INF_CREATE_NEXT_BANK_RECONCILIATION: INF_CREATE_NEXT_BANK_RECONCILIATION,
    INF_BANK_RECONCILIATION_LIST_VIEW_KOALI_MAKE_NEW: INF_BANK_RECONCILIATION_LIST_VIEW_KOALI_MAKE_NEW,
    INF_AUTO_POPULATE_FIELDS_BANK_RECONCILIATION: INF_AUTO_POPULATE_FIELDS_BANK_RECONCILIATION,
    INF_DATE_BETWEEN_STMT_BANK_RECONCILIATION: INF_DATE_BETWEEN_STMT_BANK_RECONCILIATION
}