import INF_SELECT_AMORTIZATION_METHOD from '@salesforce/label/c.INF_SELECT_AMORTIZATION_METHOD';
import INF_NO_ACTIVE_AMORTIZATION_METHOD from '@salesforce/label/c.INF_NO_ACTIVE_AMORTIZATION_METHOD';

export default {
    INF_SELECT_AMORTIZATION_METHOD: INF_SELECT_AMORTIZATION_METHOD,
    INF_NO_ACTIVE_AMORTIZATION_METHOD: INF_NO_ACTIVE_AMORTIZATION_METHOD
}