import INF_SELECT_STANDARD_REPORT from '@salesforce/label/c.INF_SELECT_STANDARD_REPORT';
import INF_PROFIT_LOSS_VS_BUDGET from '@salesforce/label/c.INF_PROFIT_LOSS_VS_BUDGET';
import INF_P_AND_L_VS_BUDGET from '@salesforce/label/c.INF_P_AND_L_VS_BUDGET';

export default {
    INF_SELECT_STANDARD_REPORT: INF_SELECT_STANDARD_REPORT,
    INF_PROFIT_LOSS_VS_BUDGET: INF_PROFIT_LOSS_VS_BUDGET,
    INF_P_AND_L_VS_BUDGET: INF_P_AND_L_VS_BUDGET
}