import INF_CREATE_HIERARCHY from '@salesforce/label/c.INF_CREATE_HIERARCHY';
import INF_ADD_LEDGER from '@salesforce/label/c.INF_ADD_LEDGER';
import INF_EDIT_LEDGER_HIERARCHY from '@salesforce/label/c.INF_EDIT_LEDGER_HIERARCHY';
import INF_REMOVE_LEDGER from '@salesforce/label/c.INF_REMOVE_LEDGER';
import WRN_CONFIGURATION_REQUIRED from '@salesforce/label/c.WRN_CONFIGURATION_REQUIRED';
import INF_CONSOLIDATION_CONFIGURATION from '@salesforce/label/c.INF_CONSOLIDATION_CONFIGURATION';
import INF_KB_ARTICLE_COMPLETE_SETUP from '@salesforce/label/c.INF_KB_ARTICLE_COMPLETE_SETUP';
import INF_NO_HIERARCHIES_TO_DISPLAY from '@salesforce/label/c.INF_NO_HIERARCHIES_TO_DISPLAY';
import INF_SMALL_CREATE from '@salesforce/label/c.INF_SMALL_CREATE';
import INF_TO_GET_STARTED from '@salesforce/label/c.INF_TO_GET_STARTED';

export default {
    INF_CREATE_HIERARCHY: INF_CREATE_HIERARCHY,
    INF_ADD_LEDGER: INF_ADD_LEDGER,
    INF_EDIT_LEDGER_HIERARCHY: INF_EDIT_LEDGER_HIERARCHY,
    INF_REMOVE_LEDGER: INF_REMOVE_LEDGER,
    WRN_CONFIGURATION_REQUIRED: WRN_CONFIGURATION_REQUIRED,
    INF_CONSOLIDATION_CONFIGURATION: INF_CONSOLIDATION_CONFIGURATION,
    INF_KB_ARTICLE_COMPLETE_SETUP: INF_KB_ARTICLE_COMPLETE_SETUP,
    INF_NO_HIERARCHIES_TO_DISPLAY: INF_NO_HIERARCHIES_TO_DISPLAY,
    INF_SMALL_CREATE: INF_SMALL_CREATE,
    INF_TO_GET_STARTED: INF_TO_GET_STARTED,
}