import INF_ISSUE_CASH_RECEIPT_REFUND from '@salesforce/label/c.INF_ISSUE_CASH_RECEIPT_REFUND';
import INF_ISSUE_CREDIT_MEMO_REFUND from '@salesforce/label/c.INF_ISSUE_CREDIT_MEMO_REFUND';
import COMMON_CASH_RECEIPT from '@salesforce/label/c.COMMON_CASH_RECEIPT';
import COMMON_CREDIT_MEMO from '@salesforce/label/c.COMMON_CREDIT_MEMO';
export default {
    INF_ISSUE_CASH_RECEIPT_REFUND : INF_ISSUE_CASH_RECEIPT_REFUND,
    INF_ISSUE_CREDIT_MEMO_REFUND : INF_ISSUE_CREDIT_MEMO_REFUND,
    COMMON_CASH_RECEIPT : COMMON_CASH_RECEIPT,
    COMMON_CREDIT_MEMO : COMMON_CREDIT_MEMO
}