import INF_SELECT_DEFAULT_1099_FORM_BOX_PAYEE_CD_PAYMENTS from '@salesforce/label/c.INF_SELECT_DEFAULT_1099_FORM_BOX_PAYEE_CD_PAYMENTS';
import INF_ENTER_DEFAULT_1099_INFORMATION from '@salesforce/label/c.INF_ENTER_DEFAULT_1099_INFORMATION';
import INF_ENABLE_1099_VENDOR from '@salesforce/label/c.INF_ENABLE_1099_VENDOR';
import INF_TAXPAYER_IDENTIFICATION_NUMBER from '@salesforce/label/c.INF_TAXPAYER_IDENTIFICATION_NUMBER';
import INF_DEFAULT_FORM_1099_TYPE from '@salesforce/label/c.INF_DEFAULT_FORM_1099_TYPE';
import INF_DEFAULT_FORM_1099_BOX from '@salesforce/label/c.INF_DEFAULT_FORM_1099_BOX';
export default {
    INF_SELECT_DEFAULT_1099_FORM_BOX_PAYEE_CD_PAYMENTS : INF_SELECT_DEFAULT_1099_FORM_BOX_PAYEE_CD_PAYMENTS,
    INF_ENTER_DEFAULT_1099_INFORMATION : INF_ENTER_DEFAULT_1099_INFORMATION,
    INF_ENABLE_1099_VENDOR : INF_ENABLE_1099_VENDOR,
    INF_TAXPAYER_IDENTIFICATION_NUMBER : INF_TAXPAYER_IDENTIFICATION_NUMBER,
    INF_DEFAULT_FORM_1099_TYPE : INF_DEFAULT_FORM_1099_TYPE,
    INF_DEFAULT_FORM_1099_BOX : INF_DEFAULT_FORM_1099_BOX
}