import INF_FILE_PREVIEW_SPINNER_TEXT from '@salesforce/label/c.INF_FILE_PREVIEW_SPINNER_TEXT';
import INF_FILE_PREVIEW_IMAGE_SPINNER_TEXT from '@salesforce/label/c.INF_FILE_PREVIEW_IMAGE_SPINNER_TEXT';
import INF_FILE_PREVIEW_BUTTON_LABEL from '@salesforce/label/c.INF_FILE_PREVIEW_BUTTON_LABEL';
import INF_FILE_PREVIEW_DEFAULT_LABEL from '@salesforce/label/c.INF_FILE_PREVIEW_DEFAULT_LABEL';
import INF_FILE_PREVIEW_ZOOM_IN_LABEL from '@salesforce/label/c.INF_FILE_PREVIEW_ZOOM_IN_LABEL';
import INF_FILE_PREVIEW_ZOOM_OUT_LABEL from '@salesforce/label/c.INF_FILE_PREVIEW_ZOOM_OUT_LABEL';
import INF_FILE_PREVIEW_NOT_AVAILABLE from '@salesforce/label/c.INF_FILE_PREVIEW_NOT_AVAILABLE';
export default {
    INF_FILE_PREVIEW_SPINNER_TEXT: INF_FILE_PREVIEW_SPINNER_TEXT,
    INF_FILE_PREVIEW_IMAGE_SPINNER_TEXT: INF_FILE_PREVIEW_IMAGE_SPINNER_TEXT,
    INF_FILE_PREVIEW_BUTTON_LABEL: INF_FILE_PREVIEW_BUTTON_LABEL,
    INF_FILE_PREVIEW_DEFAULT_LABEL: INF_FILE_PREVIEW_DEFAULT_LABEL,
    INF_FILE_PREVIEW_ZOOM_IN_LABEL: INF_FILE_PREVIEW_ZOOM_IN_LABEL,
    INF_FILE_PREVIEW_ZOOM_OUT_LABEL: INF_FILE_PREVIEW_ZOOM_OUT_LABEL,
    INF_FILE_PREVIEW_NOT_AVAILABLE: INF_FILE_PREVIEW_NOT_AVAILABLE
}