import INF_BACK_TO_TIME_CARD from '@salesforce/label/c.INF_BACK_TO_TIME_CARD';
import INF_TIME_CARD_LINES_SUCCESSFULLY_UPDATED from '@salesforce/label/c.INF_TIME_CARD_LINES_SUCCESSFULLY_UPDATED';
import COMMON_TIME_CARD_LINE from '@salesforce/label/c.COMMON_TIME_CARD_LINE';
import INF_NEW_TIME_CARD_LINE_SUCCESSFULLY_CREATED from '@salesforce/label/c.INF_NEW_TIME_CARD_LINE_SUCCESSFULLY_CREATED';
import COMMON_TIME_CARD_LINES from '@salesforce/label/c.COMMON_TIME_CARD_LINES';
import COMMON_TIME_CARDS from '@salesforce/label/c.COMMON_TIME_CARDS';
export default {
    INF_BACK_TO_TIME_CARD : INF_BACK_TO_TIME_CARD,
    INF_TIME_CARD_LINES_SUCCESSFULLY_UPDATED : INF_TIME_CARD_LINES_SUCCESSFULLY_UPDATED,
    COMMON_TIME_CARD_LINE : COMMON_TIME_CARD_LINE,
    INF_NEW_TIME_CARD_LINE_SUCCESSFULLY_CREATED : INF_NEW_TIME_CARD_LINE_SUCCESSFULLY_CREATED,
    COMMON_TIME_CARD_LINES : COMMON_TIME_CARD_LINES,
    COMMON_TIME_CARDS : COMMON_TIME_CARDS
}