import COMMON_ALL_LABEL from '@salesforce/label/c.COMMON_ALL';
import JOURNAL_ENTRY_LINE_TYPE_LABEL from '@salesforce/label/c.COMMON_JOURNAL_ENTRY_LINE';
import COMMON_TYPE from '@salesforce/label/c.COMMON_TYPE';
import COMMON_ASSOCIATE from '@salesforce/label/c.COMMON_ASSOCIATE';
import COMMON_CASH_RECEIPT from '@salesforce/label/c.COMMON_CASH_RECEIPT'
import COMMON_UNASSOCIATE from '@salesforce/label/c.COMMON_UNASSOCIATE';
import COMMON_VENDOR from '@salesforce/label/c.COMMON_VENDOR';
import RECORD_DATE_COL_FOR_BANKDISB_LWC from '@salesforce/label/c.RECORD_DATE_COL_FOR_BANKDISB_LWC';
import INF_LEDGER_AMOUNT from '@salesforce/label/c.INF_LEDGER_AMOUNT';
import COMMON_SOURCE from '@salesforce/label/c.COMMON_SOURCE';
import CUSTOMER from '@salesforce/label/c.CUSTOMER';
import COMMON_NAME from '@salesforce/label/c.COMMON_NAME';
import COMMON_REFERENCE from '@salesforce/label/c.COMMON_REFERENCE';
import COMMON_AMOUNT from '@salesforce/label/c.COMMON_AMOUNT';
import FILTER_RESULTS_HEADER from '@salesforce/label/c.FILTER_RESULTS_HEADER';
import NO_MATCHING_RECORD_FOUND from '@salesforce/label/c.NO_MATCHING_RECORD_FOUND';
import HEADER_FOR_BANK_DISBURSEMENT_MANAGER_LWC from '@salesforce/label/c.HEADER_FOR_BANK_DISBURSEMENT_MANAGER_LWC';
import AUTOMATED_JOBS_SCHEDULED_JOBS_START_DATE from '@salesforce/label/c.AUTOMATED_JOBS_SCHEDULED_JOBS_START_DATE';
import ERR_FETCHING_BANKDEPOSIT_RECORD from '@salesforce/label/c.ERR_FETCHING_BANKDEPOSIT_RECORD';
import NO_RECORDS_FOUND_LABEL_FOR_BANKDIS_MANAGER from '@salesforce/label/c.NO_RECORDS_FOUND_LABEL_FOR_BANKDIS_MANAGER';
import INFO_NO_RECORD_MSG from '@salesforce/label/c.INFO_NO_RECORD_MSG';
import ERR_IN_BANK_DEPOSIT_MANAGER_COMPONENT from '@salesforce/label/c.ERR_IN_BANK_DEPOSIT_MANAGER_COMPONENT';
import COMMON_ERROR_TEXT from '@salesforce/label/c.COMMON_ERROR_TEXT';
import SUCCESS_MSG_AFTER_ASSOCIATED_RECS_ON_BANKDISB_LWC from '@salesforce/label/c.SUCCESS_MSG_AFTER_ASSOCIATED_RECS_ON_BANKDISB_LWC';
import SUCCESS_MSG_AFTER_UNASSOCIATED_RECS_ON_BANKDISB_LWC from '@salesforce/label/c.SUCCESS_MSG_AFTER_UNASSOCIATED_RECS_ON_BANKDISB_LWC';
import commonSuccess from '@salesforce/label/c.COMMON_SUCCESS';
import BANK_DEPOSIT_AMOUNT_HEADING from '@salesforce/label/c.BANK_DEPOSIT_AMOUNT_HEADING'
import COMMON_END_DATE from '@salesforce/label/c.COMMON_END_DATE';


export const bankDepositManagerLabels = () => {
    return {
        COMMON_ALL_LABEL,
        JOURNAL_ENTRY_LINE_TYPE_LABEL,
        COMMON_ASSOCIATE,
        COMMON_UNASSOCIATE,
        NO_MATCHING_RECORD_FOUND,
        HEADER_FOR_BANK_DISBURSEMENT_MANAGER_LWC,
        AUTOMATED_JOBS_SCHEDULED_JOBS_START_DATE,
        COMMON_END_DATE,
        COMMON_CASH_RECEIPT,
        COMMON_TYPE,
        FILTER_RESULTS_HEADER,
        COMMON_VENDOR,
        RECORD_DATE_COL_FOR_BANKDISB_LWC,
        INF_LEDGER_AMOUNT,
        COMMON_REFERENCE,
        COMMON_SOURCE,
        CUSTOMER,
        COMMON_NAME,
        COMMON_AMOUNT,
        ERR_FETCHING_BANKDEPOSIT_RECORD,
        NO_RECORDS_FOUND_LABEL_FOR_BANKDIS_MANAGER,
        INFO_NO_RECORD_MSG,
        ERR_IN_BANK_DEPOSIT_MANAGER_COMPONENT,
        COMMON_ERROR_TEXT,
        SUCCESS_MSG_AFTER_ASSOCIATED_RECS_ON_BANKDISB_LWC,
        SUCCESS_MSG_AFTER_UNASSOCIATED_RECS_ON_BANKDISB_LWC,
        commonSuccess,
        BANK_DEPOSIT_AMOUNT_HEADING
    }
}