import INF_FOLLOWING_RECORDS_POSTED_SEQUENTIALLY_NOW from '@salesforce/label/c.INF_FOLLOWING_RECORDS_POSTED_SEQUENTIALLY_NOW';
import INF_JOB_RESULT_CREATED from '@salesforce/label/c.INF_JOB_RESULT_CREATED';

export default {
    INF_FOLLOWING_RECORDS_POSTED_SEQUENTIALLY_NOW: INF_FOLLOWING_RECORDS_POSTED_SEQUENTIALLY_NOW,
    INF_JOB_RESULT_CREATED: INF_JOB_RESULT_CREATED
}