import INF_SUPPRESS_OPENING_BAL_PERIOD_COLUMNS from '@salesforce/label/c.INF_SUPPRESS_OPENING_BAL_PERIOD_COLUMNS';

export default {
    INF_SUPPRESS_OPENING_BAL_PERIOD_COLUMNS: INF_SUPPRESS_OPENING_BAL_PERIOD_COLUMNS,
}