import COMMON_RELEASE from '@salesforce/label/c.COMMON_RELEASE';
import COMMON_VERSION from '@salesforce/label/c.COMMON_VERSION';
import COMMON_UNPACKAGED from '@salesforce/label/c.COMMON_UNPACKAGED';
export default {
    COMMON_RELEASE : COMMON_RELEASE,
    COMMON_VERSION : COMMON_VERSION,
    COMMON_UNPACKAGED : COMMON_UNPACKAGED
}