import ERR_LOADING_ASSOCIATED_ITEMS from '@salesforce/label/c.ERR_LOADING_ASSOCIATED_ITEMS';
import WRN_CHANGE_BANK_RECONCILIATION_STATUS_COMPLETED from '@salesforce/label/c.WRN_CHANGE_BANK_RECONCILIATION_STATUS_COMPLETED';
import WRN_CHANGE_BANK_RECONCILIATION_STATUS_IN_PROGRESS from '@salesforce/label/c.WRN_CHANGE_BANK_RECONCILIATION_STATUS_IN_PROGRESS';
import WRN_CLEAR_ALL_RECORDS_ON_PAGE from '@salesforce/label/c.WRN_CLEAR_ALL_RECORDS_ON_PAGE';
import WRN_UNCLEAR_ALL_RECORDS_ON_PAGE from '@salesforce/label/c.WRN_UNCLEAR_ALL_RECORDS_ON_PAGE';
import INF_UNCLEAR_ALL from '@salesforce/label/c.INF_UNCLEAR_ALL';
import INF_CLEAR_ALL from '@salesforce/label/c.INF_CLEAR_ALL';
import INF_MORE_THAN from '@salesforce/label/c.INF_MORE_THAN';
import INF_TRANSACTION_IS_VOIDED from '@salesforce/label/c.INF_TRANSACTION_IS_VOIDED';
import INF_AUTO_CLEAR_BUTTON_TITLE from '@salesforce/label/c.INF_AUTO_CLEAR_BUTTON_TITLE';
import INF_CLEAR_BANK_DATES from '@salesforce/label/c.INF_CLEAR_BANK_DATES';
import INF_SET_TO_IN_PROGRESS from '@salesforce/label/c.INF_SET_TO_IN_PROGRESS';
import INF_SET_TO_COMPLETED from '@salesforce/label/c.INF_SET_TO_COMPLETED';
import INF_BANK_TRANSACTION_DATE from '@salesforce/label/c.INF_BANK_TRANSACTION_DATE';
import INF_SOURCE_LINK from '@salesforce/label/c.INF_SOURCE_LINK';
import INF_REF from '@salesforce/label/c.INF_REF';
import INF_LEDGER_AMOUNT from '@salesforce/label/c.INF_LEDGER_AMOUNT';
import WRN_CLEARED_MESSAGE_TEMPLATE_RECONCILITION from '@salesforce/label/c.WRN_CLEARED_MESSAGE_TEMPLATE_RECONCILITION';
import WRN_TRANSACTION_VOIDED_RECONCILITION from '@salesforce/label/c.WRN_TRANSACTION_VOIDED_RECONCILITION';
import WRN_LEGACY_BD_MESSAGE from '@salesforce/label/c.WRN_LEGACY_BD_MESSAGE';
import ERR_BANK_RECONCILIATION_LIMIT_EXCEEDED from '@salesforce/label/c.ERR_BANK_RECONCILIATION_LIMIT_EXCEEDED';
import WRN_TRN_CLEARED_TITLE_RECONCILITION from '@salesforce/label/c.WRN_TRN_CLEARED_TITLE_RECONCILITION';
import INF_TRANSFER from '@salesforce/label/c.INF_TRANSFER';
import INF_TRANSACTION_IS_CLEARED from '@salesforce/label/c.INF_TRANSACTION_IS_CLEARED';
import WRN_RECONCILIATION_JOB_PROGRESS_PLEASE_WAIT from '@salesforce/label/c.WRN_RECONCILIATION_JOB_PROGRESS_PLEASE_WAIT';

export default {
    ERR_LOADING_ASSOCIATED_ITEMS: ERR_LOADING_ASSOCIATED_ITEMS,
    WRN_CHANGE_BANK_RECONCILIATION_STATUS_COMPLETED: WRN_CHANGE_BANK_RECONCILIATION_STATUS_COMPLETED,
    WRN_CHANGE_BANK_RECONCILIATION_STATUS_IN_PROGRESS: WRN_CHANGE_BANK_RECONCILIATION_STATUS_IN_PROGRESS,
    WRN_CLEAR_ALL_RECORDS_ON_PAGE: WRN_CLEAR_ALL_RECORDS_ON_PAGE,
    WRN_UNCLEAR_ALL_RECORDS_ON_PAGE: WRN_UNCLEAR_ALL_RECORDS_ON_PAGE,
    INF_UNCLEAR_ALL: INF_UNCLEAR_ALL,
    INF_CLEAR_ALL: INF_CLEAR_ALL,
    INF_MORE_THAN: INF_MORE_THAN,
    INF_TRANSACTION_IS_VOIDED: INF_TRANSACTION_IS_VOIDED,
    INF_AUTO_CLEAR_BUTTON_TITLE: INF_AUTO_CLEAR_BUTTON_TITLE,
    INF_CLEAR_BANK_DATES: INF_CLEAR_BANK_DATES,
    INF_SET_TO_IN_PROGRESS: INF_SET_TO_IN_PROGRESS,
    INF_SET_TO_COMPLETED: INF_SET_TO_COMPLETED,
    INF_BANK_TRANSACTION_DATE: INF_BANK_TRANSACTION_DATE,
    INF_SOURCE_LINK: INF_SOURCE_LINK,
    INF_REF: INF_REF,
    INF_LEDGER_AMOUNT: INF_LEDGER_AMOUNT,
    WRN_CLEARED_MESSAGE_TEMPLATE_RECONCILITION: WRN_CLEARED_MESSAGE_TEMPLATE_RECONCILITION,
    WRN_TRANSACTION_VOIDED_RECONCILITION: WRN_TRANSACTION_VOIDED_RECONCILITION,
    WRN_LEGACY_BD_MESSAGE: WRN_LEGACY_BD_MESSAGE,
    ERR_BANK_RECONCILIATION_LIMIT_EXCEEDED: ERR_BANK_RECONCILIATION_LIMIT_EXCEEDED,
    WRN_TRN_CLEARED_TITLE_RECONCILITION: WRN_TRN_CLEARED_TITLE_RECONCILITION,
    INF_TRANSFER: INF_TRANSFER,
    INF_TRANSACTION_IS_CLEARED: INF_TRANSACTION_IS_CLEARED,
    WRN_RECONCILIATION_JOB_PROGRESS_PLEASE_WAIT: WRN_RECONCILIATION_JOB_PROGRESS_PLEASE_WAIT
}