import ERR_SELECT_AMORTIZATION_METHOD_TO_VIEW from '@salesforce/label/c.ERR_SELECT_AMORTIZATION_METHOD_TO_VIEW';
import INF_ENTRIES_POST_POST_SETTINGS from '@salesforce/label/c.INF_ENTRIES_POST_POST_SETTINGS';
import INF_SELECT_METHOD_TEXT from '@salesforce/label/c.INF_SELECT_METHOD_TEXT';
import INF_TERM_INFORMATION from '@salesforce/label/c.INF_TERM_INFORMATION';
import INF_ACCOUNTING_INFORMATION_AND_CREATE from '@salesforce/label/c.INF_ACCOUNTING_INFORMATION_AND_CREATE';
import INF_AMORTIZATION_ENTRIES_CREATED_POSTED from '@salesforce/label/c.INF_AMORTIZATION_ENTRIES_CREATED_POSTED';
import INF_AMORTIZATION_ENTRIES_CREATED_AND_POSTING_SHOULD_BE_DONE from '@salesforce/label/c.INF_AMORTIZATION_ENTRIES_CREATED_AND_POSTING_SHOULD_BE_DONE';
import INF_CREATE_AMORTIZATION_ENTRIES from '@salesforce/label/c.INF_CREATE_AMORTIZATION_ENTRIES';

export default {
    ERR_SELECT_AMORTIZATION_METHOD_TO_VIEW: ERR_SELECT_AMORTIZATION_METHOD_TO_VIEW,
    INF_ENTRIES_POST_POST_SETTINGS: INF_ENTRIES_POST_POST_SETTINGS,
    INF_SELECT_METHOD_TEXT: INF_SELECT_METHOD_TEXT,
    INF_TERM_INFORMATION: INF_TERM_INFORMATION,
    INF_ACCOUNTING_INFORMATION_AND_CREATE: INF_ACCOUNTING_INFORMATION_AND_CREATE,
    INF_AMORTIZATION_ENTRIES_CREATED_POSTED: INF_AMORTIZATION_ENTRIES_CREATED_POSTED,
    INF_AMORTIZATION_ENTRIES_CREATED_AND_POSTING_SHOULD_BE_DONE: INF_AMORTIZATION_ENTRIES_CREATED_AND_POSTING_SHOULD_BE_DONE,
    INF_CREATE_AMORTIZATION_ENTRIES: INF_CREATE_AMORTIZATION_ENTRIES
}