import ERR_INCORRECT_BILLING_TYPE_INVOICE from '@salesforce/label/c.ERR_INCORRECT_BILLING_TYPE_INVOICE';
import ERR_PLEASE_CORRECT_ERROR_FOR_BILLING from '@salesforce/label/c.ERR_PLEASE_CORRECT_ERROR_FOR_BILLING';

export default {
    ERR_INCORRECT_BILLING_TYPE_INVOICE: ERR_INCORRECT_BILLING_TYPE_INVOICE,
    ERR_PLEASE_CORRECT_ERROR_FOR_BILLING: ERR_PLEASE_CORRECT_ERROR_FOR_BILLING
}