import ERR_RUNNING_CONSOLIDATION_ROUTINE from '@salesforce/label/c.ERR_RUNNING_CONSOLIDATION_ROUTINE';
import WRN_ASSIGN_PERMISSION_RUN_CONSOLIDATION_ROUTINE from '@salesforce/label/c.WRN_ASSIGN_PERMISSION_RUN_CONSOLIDATION_ROUTINE';

export default {
    ERR_RUNNING_CONSOLIDATION_ROUTINE: ERR_RUNNING_CONSOLIDATION_ROUTINE,
    WRN_ASSIGN_PERMISSION_RUN_CONSOLIDATION_ROUTINE: WRN_ASSIGN_PERMISSION_RUN_CONSOLIDATION_ROUTINE
}