import COMMON_SELECTED_ITEM_ICON from '@salesforce/label/c.COMMON_SELECTED_ITEM_ICON';
import COMMON_SEARCH_ICON from '@salesforce/label/c.COMMON_SEARCH_ICON';
import COMMON_RECENT_RECORDS from '@salesforce/label/c.COMMON_RECENT_RECORDS';
import COMMON_RESULT_ITEM_ICON from '@salesforce/label/c.COMMON_RESULT_ITEM_ICON';
export default {
    COMMON_SELECTED_ITEM_ICON : COMMON_SELECTED_ITEM_ICON,
    COMMON_SEARCH_ICON : COMMON_SEARCH_ICON,
    COMMON_RECENT_RECORDS : COMMON_RECENT_RECORDS,
    COMMON_RESULT_ITEM_ICON : COMMON_RESULT_ITEM_ICON
}