import WRN_RECONCILIATION_PDF_SUMMARY_CANNOT_GENERATED from '@salesforce/label/c.WRN_RECONCILIATION_PDF_SUMMARY_CANNOT_GENERATED';
import WRN_CSV_BANK_RECONCILIATION_NOT_SUPPORTED_KOALI from '@salesforce/label/c.WRN_CSV_BANK_RECONCILIATION_NOT_SUPPORTED_KOALI';
import INF_A_BANK_RECONCILIATION from '@salesforce/label/c.INF_A_BANK_RECONCILIATION';
import INF_WAS_SUCCESSFULLY_GENERATED from '@salesforce/label/c.INF_WAS_SUCCESSFULLY_GENERATED';
import INF_CREATE_BANK_RECONCILIATION from '@salesforce/label/c.INF_CREATE_BANK_RECONCILIATION';
import INF_PLEASE_CHECK_NOTES_FILES_LATER from '@salesforce/label/c.INF_PLEASE_CHECK_NOTES_FILES_LATER';
import INF_WILL_GENERATE_BANK_RECONCILIATION from '@salesforce/label/c.INF_WILL_GENERATE_BANK_RECONCILIATION';
import INF_ANY_CHANGES_TO_GL_NOT_REFLECTED_IN_THIS from '@salesforce/label/c.INF_ANY_CHANGES_TO_GL_NOT_REFLECTED_IN_THIS';

export default {
    WRN_RECONCILIATION_PDF_SUMMARY_CANNOT_GENERATED: WRN_RECONCILIATION_PDF_SUMMARY_CANNOT_GENERATED,
    WRN_CSV_BANK_RECONCILIATION_NOT_SUPPORTED_KOALI: WRN_CSV_BANK_RECONCILIATION_NOT_SUPPORTED_KOALI,
    INF_A_BANK_RECONCILIATION: INF_A_BANK_RECONCILIATION,
    INF_WAS_SUCCESSFULLY_GENERATED: INF_WAS_SUCCESSFULLY_GENERATED,
    INF_CREATE_BANK_RECONCILIATION: INF_CREATE_BANK_RECONCILIATION,
    INF_PLEASE_CHECK_NOTES_FILES_LATER: INF_PLEASE_CHECK_NOTES_FILES_LATER,
    INF_WILL_GENERATE_BANK_RECONCILIATION: INF_WILL_GENERATE_BANK_RECONCILIATION,
    INF_ANY_CHANGES_TO_GL_NOT_REFLECTED_IN_THIS: INF_ANY_CHANGES_TO_GL_NOT_REFLECTED_IN_THIS
}