import AMORTIZATION_ENTRY from '@salesforce/schema/Scheduled_Revenue_Expense__c';
import AMOUNT from '@salesforce/schema/Scheduled_Revenue_Expense__c.Amount__c';
import DESCRIPTION from '@salesforce/schema/Scheduled_Revenue_Expense__c.Description__c';
import DEBIT_GL_ACCOUNT from '@salesforce/schema/Scheduled_Revenue_Expense__c.Debit_GL_Account__c';
import DEBIT_GL_ACCOUNT_R_NAME from '@salesforce/schema/Scheduled_Revenue_Expense__c.Debit_GL_Account__r.Name';
import CREDIT_GL_ACCOUNT from '@salesforce/schema/Scheduled_Revenue_Expense__c.Credit_GL_Account__c';
import CREDIT_GL_ACCOUNT_R_NAME from '@salesforce/schema/Scheduled_Revenue_Expense__c.Credit_GL_Account__r.Name';
import PRODUCT from '@salesforce/schema/Scheduled_Revenue_Expense__c.Product__c';
import PRODUCT_R_NAME from '@salesforce/schema/Scheduled_Revenue_Expense__c.Product__r.Name';
import PROJECT from '@salesforce/schema/Scheduled_Revenue_Expense__c.Project__c';
import PROJECT_R_NAME from '@salesforce/schema/Scheduled_Revenue_Expense__c.Project__r.Name';
import PROJECT_TASK from '@salesforce/schema/Scheduled_Revenue_Expense__c.Project_Task__c';
import PROJECT_TASK_R_NAME from '@salesforce/schema/Scheduled_Revenue_Expense__c.Project_Task__r.Name';
import GL_VARIABLE1 from '@salesforce/schema/Scheduled_Revenue_Expense__c.GL_Account_Variable_1__c';
import GL_VARIABLE1_R_NAME from '@salesforce/schema/Scheduled_Revenue_Expense__c.GL_Account_Variable_1__r.Name';
import GL_VARIABLE2 from '@salesforce/schema/Scheduled_Revenue_Expense__c.GL_Account_Variable_2__c';
import GL_VARIABLE2_R_NAME from '@salesforce/schema/Scheduled_Revenue_Expense__c.GL_Account_Variable_2__r.Name';
import GL_VARIABLE3 from '@salesforce/schema/Scheduled_Revenue_Expense__c.GL_Account_Variable_3__c';
import GL_VARIABLE3_R_NAME from '@salesforce/schema/Scheduled_Revenue_Expense__c.GL_Account_Variable_3__r.Name';
import GL_VARIABLE4 from '@salesforce/schema/Scheduled_Revenue_Expense__c.GL_Account_Variable_4__c';
import GL_VARIABLE4_R_NAME from '@salesforce/schema/Scheduled_Revenue_Expense__c.GL_Account_Variable_4__r.Name';
import ACCRUAL_CASH from '@salesforce/schema/Scheduled_Revenue_Expense__c.Accrual_and_or_Cash__c';

export default class AmortizationEntry {
    static objectApiName = AMORTIZATION_ENTRY.objectApiName;

    static amount = AMOUNT;
    static description = DESCRIPTION;
    static debit_gl_account = DEBIT_GL_ACCOUNT;
    static debit_gl_account_r_name = DEBIT_GL_ACCOUNT_R_NAME;
    static credit_gl_account = CREDIT_GL_ACCOUNT;
    static credit_gl_account_r_name = CREDIT_GL_ACCOUNT_R_NAME;
    static product = PRODUCT;
    static product_r_name = PRODUCT_R_NAME;
    static project = PROJECT;
    static project_r_name = PROJECT_R_NAME;
    static project_task = PROJECT_TASK;
    static project_task_r_name = PROJECT_TASK_R_NAME;
    static gl_variable1 = GL_VARIABLE1;
    static gl_variable1_r_name = GL_VARIABLE1_R_NAME;
    static gl_variable2 = GL_VARIABLE2;
    static gl_variable2_r_name = GL_VARIABLE2_R_NAME;
    static gl_variable3 = GL_VARIABLE3;
    static gl_variable3_r_name = GL_VARIABLE3_R_NAME;
    static gl_variable4 = GL_VARIABLE4;
    static gl_variable4_r_name = GL_VARIABLE4_R_NAME;
    static accrual_cash = ACCRUAL_CASH;

    amount = AMOUNT.fieldApiName;
    description = DESCRIPTION.fieldApiName;
    debit_gl_account = DEBIT_GL_ACCOUNT.fieldApiName;
    debit_gl_account_r_name = DEBIT_GL_ACCOUNT_R_NAME.fieldApiName;
    credit_gl_account = CREDIT_GL_ACCOUNT.fieldApiName;
    credit_gl_account_r_name = CREDIT_GL_ACCOUNT_R_NAME.fieldApiName;
    product = PRODUCT.fieldApiName;
    product_r_name = PRODUCT_R_NAME.fieldApiName;
    project = PROJECT.fieldApiName;
    project_r_name = PROJECT_R_NAME.fieldApiName;
    project_task = PROJECT_TASK.fieldApiName;
    project_task_r_name = PROJECT_TASK_R_NAME.fieldApiName;
    gl_variable1 = GL_VARIABLE1.fieldApiName;
    gl_variable1_r_name = GL_VARIABLE1_R_NAME.fieldApiName;
    gl_variable2 = GL_VARIABLE2.fieldApiName;
    gl_variable2_r_name = GL_VARIABLE2_R_NAME.fieldApiName;
    gl_variable3 = GL_VARIABLE3.fieldApiName;
    gl_variable3_r_name = GL_VARIABLE3_R_NAME.fieldApiName;
    gl_variable4 = GL_VARIABLE4.fieldApiName;
    gl_variable4_r_name = GL_VARIABLE4_R_NAME.fieldApiName;
    accrual_cash = ACCRUAL_CASH.fieldApiName;
}