import BILLING from '@salesforce/schema/Billing__c';
import NAME_FIELD from '@salesforce/schema/Billing__c.Name';
import PROPRIETARY_BILLING_NUMBER from '@salesforce/schema/Billing__c.Proprietary_Billing_Number__c';
import BILLING_CYCLE_START_DATE from '@salesforce/schema/Billing__c.Billing_Cycle_Start_Date__c';
import BILLING_CYCLE_END_DATE from '@salesforce/schema/Billing__c.Billing_Cycle_End_Date__c';
import DATE from '@salesforce/schema/Billing__c.Date__c';
import CUSTOMER from '@salesforce/schema/Billing__c.Customer__c';
import TOTAL from '@salesforce/schema/Billing__c.Total__c';
import SUB_TOTAL from '@salesforce/schema/Billing__c.Sub_Total__c';
import BALANCE from '@salesforce/schema/Billing__c.Balance__c';
import RECEIVED_AMOUNT from '@salesforce/schema/Billing__c.Received_Amount__c';
import TYPE from '@salesforce/schema/Billing__c.Type__c';
import STATUS from '@salesforce/schema/Billing__c.Status__c';
import CUSTOMER_R_NAME from '@salesforce/schema/Billing__c.Customer__r.Name';
import LEDGER from '@salesforce/schema/Billing__c.Ledger__c';
import LEDGER_R_NAME from '@salesforce/schema/Billing__c.Ledger__r.Name';
import LEDGER_R_ACCT_METHOD from '@salesforce/schema/Billing__c.Ledger__r.Accounting_Method__c';
import B_COMMENT from '@salesforce/schema/Billing__c.Billing_Comment__c';
import B_STREET from '@salesforce/schema/Billing__c.Billing_Street__c';
import B_CITY from '@salesforce/schema/Billing__c.Billing_City__c';
import B_STATE from '@salesforce/schema/Billing__c.Billing_State__c';
import B_POSTAL_CODE from '@salesforce/schema/Billing__c.Billing_PostalCode__c';
import B_COUNTRY from '@salesforce/schema/Billing__c.Billing_Country__c';
import S_STREET from '@salesforce/schema/Billing__c.Shipping_Street__c';
import S_CITY from '@salesforce/schema/Billing__c.Shipping_City__c';
import S_STATE from '@salesforce/schema/Billing__c.Shipping_State__c';
import S_POSTAL_CODE from '@salesforce/schema/Billing__c.Shipping_PostalCode__c';
import S_COUNTRY from '@salesforce/schema/Billing__c.Shipping_Country__c';
import CREDIT_MEMO_REASON from '@salesforce/schema/Billing__c.Credit_Memo_Reason__c';
import CREDIT_MEMO_APPLIED_AMOUNT from '@salesforce/schema/Billing__c.Credit_Memo_Applied_Amount__c';
import BILLING_COMMENT from '@salesforce/schema/Billing__c.Billing_Comment__c';
import LEDGER_AMOUNT from '@salesforce/schema/Billing__c.Ledger_Amount__c';
import SALES_TAX2 from '@salesforce/schema/Billing__c.Sales_Tax2__c';
import SALES_TAX3 from '@salesforce/schema/Billing__c.Sales_Tax3__c';

export default class Billing {
    static objectApiName = BILLING.objectApiName;

    static name_field = NAME_FIELD;
    static proprietary_billing_number = PROPRIETARY_BILLING_NUMBER;
    static billing_cycle_start_date = BILLING_CYCLE_START_DATE;
    static billing_cycle_end_date = BILLING_CYCLE_END_DATE;
    static date = DATE;
    static customer = CUSTOMER;
    static total = TOTAL;
    static received_amount = RECEIVED_AMOUNT;
    static balance = BALANCE;
    static type = TYPE;
    static status = STATUS;
    static customer_r_name = CUSTOMER_R_NAME;
    static ledger = LEDGER;
    static ledger_r_name = LEDGER_R_NAME;
    static ledger_r_acct_method = LEDGER_R_ACCT_METHOD;
    static bComment = B_COMMENT;
    static bStreet = B_STREET;
    static bCity = B_CITY;
    static bState = B_STATE;
    static bPostalCode = B_POSTAL_CODE;
    static bCountry = B_COUNTRY;
    static sStreet = S_STREET;
    static sCity = S_CITY;
    static sState = S_STATE;
    static sPostalCode = S_POSTAL_CODE;
    static sCountry = S_COUNTRY;
    static credit_memo_reason = CREDIT_MEMO_REASON;
    static credit_memo_applied_amount = CREDIT_MEMO_APPLIED_AMOUNT;
    static billing_comment = BILLING_COMMENT;
    static ledger_amount = LEDGER_AMOUNT;
    static sub_total = SUB_TOTAL;
    static sales_tax2 = SALES_TAX2;
    static sales_tax3 = SALES_TAX3;

    name_field = NAME_FIELD.fieldApiName;
    proprietary_billing_number = PROPRIETARY_BILLING_NUMBER.fieldApiName;
    billing_cycle_start_date = BILLING_CYCLE_START_DATE.fieldApiName;
    billing_cycle_end_date = BILLING_CYCLE_END_DATE.fieldApiName;
    date = DATE.fieldApiName;
    customer = CUSTOMER.fieldApiName;
    total = TOTAL.fieldApiName;
    customer_r_name = CUSTOMER_R_NAME.fieldApiName;
    ledger = LEDGER.fieldApiName;
    ledger_r_name = LEDGER_R_NAME.fieldApiName;
    ledger_r_acct_method = LEDGER_R_ACCT_METHOD.fieldApiName;
    bStreet = B_STREET.fieldApiName;
    bCity = B_CITY.fieldApiName;
    bState = B_STATE.fieldApiName;
    bPostalCode = B_POSTAL_CODE.fieldApiName;
    bCountry = B_COUNTRY.fieldApiName;
    sStreet = S_STREET.fieldApiName;
    sCity = S_CITY.fieldApiName;
    sState = S_STATE.fieldApiName;
    sPostalCode = S_POSTAL_CODE.fieldApiName;
    sCountry = S_COUNTRY.fieldApiName;
    credit_memo_reason = CREDIT_MEMO_REASON.fieldApiName;
    credit_memo_applied_amount = CREDIT_MEMO_APPLIED_AMOUNT.fieldApiName;
    billing_comment = BILLING_COMMENT.fieldApiName;
    ledger_amount = LEDGER_AMOUNT.fieldApiName;
    sub_total = SUB_TOTAL.fieldApiName;
    sales_tax2 = SALES_TAX2.fieldApiName;
    sales_tax3 = SALES_TAX3.fieldApiName;
}