import INF_EDIT_TIME_CARD_LINE from '@salesforce/label/c.INF_EDIT_TIME_CARD_LINE';
import INF_NEW_TIME_CARD_LINE from '@salesforce/label/c.INF_NEW_TIME_CARD_LINE';
import INF_TIME_CARD_LINE_NOT_SAVED from '@salesforce/label/c.INF_TIME_CARD_LINE_NOT_SAVED';
export default {
    INF_EDIT_TIME_CARD_LINE : INF_EDIT_TIME_CARD_LINE,
    INF_NEW_TIME_CARD_LINE : INF_NEW_TIME_CARD_LINE,
    INF_TIME_CARD_LINE_NOT_SAVED : INF_TIME_CARD_LINE_NOT_SAVED
}