import INF_LEDGER_VALUE_REQUIRED_TO_ESTIMATE_TAXES from '@salesforce/label/c.INF_LEDGER_VALUE_REQUIRED_TO_ESTIMATE_TAXES';
import COMMON_ERR_TAX_SETTING_LEDGER from '@salesforce/label/c.COMMON_ERR_TAX_SETTING_LEDGER';
import INF_NO_LINES_TO_DISPLAY from '@salesforce/label/c.INF_NO_LINES_TO_DISPLAY';
export default {
    INF_LEDGER_VALUE_REQUIRED_TO_ESTIMATE_TAXES : INF_LEDGER_VALUE_REQUIRED_TO_ESTIMATE_TAXES,
    COMMON_ERR_TAX_SETTING_LEDGER : COMMON_ERR_TAX_SETTING_LEDGER,
    INF_NO_LINES_TO_DISPLAY : INF_NO_LINES_TO_DISPLAY
}