import INF_TERM_INFORMATION from '@salesforce/label/c.INF_TERM_INFORMATION';
import INF_SUM_AMORTIZATION_ENTRIES_AMOUNT_GREATER_TOTAL from '@salesforce/label/c.INF_SUM_AMORTIZATION_ENTRIES_AMOUNT_GREATER_TOTAL';
import INF_REVENUE_EXPENSE_AMOUNT_AMORTIZED from '@salesforce/label/c.INF_REVENUE_EXPENSE_AMOUNT_AMORTIZED';
import INF_NUMBER_ACCOUNTING_PERIODS_AMORTIZED from '@salesforce/label/c.INF_NUMBER_ACCOUNTING_PERIODS_AMORTIZED';
import INF_DAY_TO_START_AMORTIZING from '@salesforce/label/c.INF_DAY_TO_START_AMORTIZING';
import ERR_NO_OPEN_ACCOUNTING_PERIOD_IN_DATE_RANGE_AMORTIZATION from '@salesforce/label/c.ERR_NO_OPEN_ACCOUNTING_PERIOD_IN_DATE_RANGE_AMORTIZATION';
import INF_DAILY_AMORTIZATION_METHOD_CALCULATE_DAYS from '@salesforce/label/c.INF_DAILY_AMORTIZATION_METHOD_CALCULATE_DAYS';
import INF_VALUE_MUST_BE from '@salesforce/label/c.INF_VALUE_MUST_BE';
import INF_OR_LATER from '@salesforce/label/c.INF_OR_LATER';
import AMORTIZE_DEFERRED_REVENUE_EXPENSE from '@salesforce/label/c.AMORTIZE_DEFERRED_REVENUE_EXPENSE';
import DEFAULT_REVENUE_GL_ACCOUNT_LINES_ONLY_HELPTEXT from '@salesforce/label/c.DEFAULT_REVENUE_GL_ACCOUNT_LINES_ONLY_HELPTEXT';

export default {
    INF_TERM_INFORMATION: INF_TERM_INFORMATION,
    INF_SUM_AMORTIZATION_ENTRIES_AMOUNT_GREATER_TOTAL: INF_SUM_AMORTIZATION_ENTRIES_AMOUNT_GREATER_TOTAL,
    INF_REVENUE_EXPENSE_AMOUNT_AMORTIZED: INF_REVENUE_EXPENSE_AMOUNT_AMORTIZED,
    INF_NUMBER_ACCOUNTING_PERIODS_AMORTIZED: INF_NUMBER_ACCOUNTING_PERIODS_AMORTIZED,
    INF_DAY_TO_START_AMORTIZING: INF_DAY_TO_START_AMORTIZING,
    INF_DAILY_AMORTIZATION_METHOD_CALCULATE_DAYS: INF_DAILY_AMORTIZATION_METHOD_CALCULATE_DAYS,
    ERR_NO_OPEN_ACCOUNTING_PERIOD_IN_DATE_RANGE_AMORTIZATION: ERR_NO_OPEN_ACCOUNTING_PERIOD_IN_DATE_RANGE_AMORTIZATION,
    INF_VALUE_MUST_BE: INF_VALUE_MUST_BE,
    INF_OR_LATER: INF_OR_LATER,
    AMORTIZE_DEFERRED_REVENUE_EXPENSE,
    DEFAULT_REVENUE_GL_ACCOUNT_LINES_ONLY_HELPTEXT
}