import INF_CANCEL_ALL from '@salesforce/label/c.INF_CANCEL_ALL';
import WRN_NO_RECORDS_FOUND from '@salesforce/label/c.WRN_NO_RECORDS_FOUND';
import INF_EXPAND_ALL_OR_COLLAPSE_ALL from '@salesforce/label/c.INF_EXPAND_ALL_OR_COLLAPSE_ALL';
import INF_MENU_LOWERCASE from '@salesforce/label/c.INF_MENU_LOWERCASE';

export default {
    INF_CANCEL_ALL: INF_CANCEL_ALL,
    WRN_NO_RECORDS_FOUND: WRN_NO_RECORDS_FOUND,
    INF_EXPAND_ALL_OR_COLLAPSE_ALL: INF_EXPAND_ALL_OR_COLLAPSE_ALL,
    INF_MENU_LOWERCASE: INF_MENU_LOWERCASE
}