import ERR_NOT_AUTHENTICATE_ACCOUNT_AVALARA_SERVICE from '@salesforce/label/c.ERR_NOT_AUTHENTICATE_ACCOUNT_AVALARA_SERVICE';
import INF_CREDENTIAL_SUCCESSFULLY_AUTHENTICATED from '@salesforce/label/c.INF_CREDENTIAL_SUCCESSFULLY_AUTHENTICATED';
import INF_AUTHENTICATION_TYPE from '@salesforce/label/c.INF_AUTHENTICATION_TYPE';
import INF_AVALARA_ACCOUNT_ID from '@salesforce/label/c.INF_AVALARA_ACCOUNT_ID';
export default {
    ERR_NOT_AUTHENTICATE_ACCOUNT_AVALARA_SERVICE : ERR_NOT_AUTHENTICATE_ACCOUNT_AVALARA_SERVICE,
    INF_CREDENTIAL_SUCCESSFULLY_AUTHENTICATED : INF_CREDENTIAL_SUCCESSFULLY_AUTHENTICATED,
    INF_AUTHENTICATION_TYPE : INF_AUTHENTICATION_TYPE,
    INF_AVALARA_ACCOUNT_ID : INF_AVALARA_ACCOUNT_ID
}