import INF_VOID_A_CASH_RECEIPT from '@salesforce/label/c.INF_VOID_A_CASH_RECEIPT';
import INF_VOID_RECEIPT_DATE from '@salesforce/label/c.INF_VOID_RECEIPT_DATE';
import INF_VOID_RECEIPT_DATE_HELP_TEXT from '@salesforce/label/c.INF_VOID_RECEIPT_DATE_HELP_TEXT';
import COMMON_CANCEL from '@salesforce/label/c.COMMON_CANCEL';
import COMMON_VOID from '@salesforce/label/c.COMMON_VOID';
import INF_THE_CASH_RECEIPT_WAS_VOIDED from '@salesforce/label/c.INF_THE_CASH_RECEIPT_WAS_VOIDED';
import INF_CARDKNOX_VOID_UI_MESSAGE from '@salesforce/label/c.INF_CARDKNOX_VOID_UI_MESSAGE';
import INF_STRIPE_VOID_UI_MESSAGE from '@salesforce/label/c.INF_STRIPE_VOID_UI_MESSAGE';

export default {
    INF_VOID_A_CASH_RECEIPT : INF_VOID_A_CASH_RECEIPT,
    INF_VOID_RECEIPT_DATE : INF_VOID_RECEIPT_DATE,
    INF_VOID_RECEIPT_DATE_HELP_TEXT : INF_VOID_RECEIPT_DATE_HELP_TEXT,
    COMMON_CANCEL : COMMON_CANCEL,
    COMMON_VOID : COMMON_VOID,
    INF_THE_CASH_RECEIPT_WAS_VOIDED : INF_THE_CASH_RECEIPT_WAS_VOIDED,
    INF_STRIPE_VOID_UI_MESSAGE : INF_STRIPE_VOID_UI_MESSAGE,
    INF_CARDKNOX_VOID_UI_MESSAGE : INF_CARDKNOX_VOID_UI_MESSAGE
}