import INF_EXPENSE_LINE from '@salesforce/label/c.INF_EXPENSE_LINE';
import INF_EXPENSE_LINES from '@salesforce/label/c.INF_EXPENSE_LINES';
import INF_EXPENSE_REPORTS from '@salesforce/label/c.INF_EXPENSE_REPORTS';
import INF_BACK_TO_EXPENSE_REPORT from '@salesforce/label/c.INF_BACK_TO_EXPENSE_REPORT';
import INF_EXPENSE_LINES_SUCCESSFULLY_UPDATED from '@salesforce/label/c.INF_EXPENSE_LINES_SUCCESSFULLY_UPDATED';
import INF_EXPENSE_LINES_SUCCESSFULLY_CREATTED from '@salesforce/label/c.INF_EXPENSE_LINES_SUCCESSFULLY_CREATTED';


export default {
    INF_EXPENSE_LINE: INF_EXPENSE_LINE,
    INF_EXPENSE_LINES: INF_EXPENSE_LINES,
    INF_EXPENSE_REPORTS: INF_EXPENSE_REPORTS,
    INF_BACK_TO_EXPENSE_REPORT: INF_BACK_TO_EXPENSE_REPORT,
    INF_EXPENSE_LINES_SUCCESSFULLY_UPDATED: INF_EXPENSE_LINES_SUCCESSFULLY_UPDATED,
    INF_EXPENSE_LINES_SUCCESSFULLY_CREATTED: INF_EXPENSE_LINES_SUCCESSFULLY_CREATTED
}