import ERR_EMPLOYEE_CREDIT_CARD_VENDOR from '@salesforce/label/c.ERR_EMPLOYEE_CREDIT_CARD_VENDOR';
import INF_EDIT_EXPENSE_LINE from '@salesforce/label/c.INF_EDIT_EXPENSE_LINE';
import INF_NEW_EXPENSE_LINE from '@salesforce/label/c.INF_NEW_EXPENSE_LINE';
import INF_EXPENSE_LINE_NOT_SAVED from '@salesforce/label/c.INF_EXPENSE_LINE_NOT_SAVED';
import INF_SELECT_CREDIT_CARD_VENDOR from '@salesforce/label/c.INF_SELECT_CREDIT_CARD_VENDOR';
import INF_SELECT_EXPENSE_TYPE from '@salesforce/label/c.INF_SELECT_EXPENSE_TYPE';
import ERR_EXPENSE_TYPE_REQ from '@salesforce/label/c.ERR_EXPENSE_TYPE_REQ';
import ERR_MILEAGE_ORIGIN_REQ from '@salesforce/label/c.ERR_MILEAGE_ORIGIN_REQ';
import ERR_MILEAGE_DESTINATION_REQ from '@salesforce/label/c.ERR_MILEAGE_DESTINATION_REQ';
import ERR_MILES_REQ from '@salesforce/label/c.ERR_MILES_REQ';

export default {
    ERR_EMPLOYEE_CREDIT_CARD_VENDOR: ERR_EMPLOYEE_CREDIT_CARD_VENDOR,
    INF_EDIT_EXPENSE_LINE: INF_EDIT_EXPENSE_LINE,
    INF_NEW_EXPENSE_LINE: INF_NEW_EXPENSE_LINE,
    INF_EXPENSE_LINE_NOT_SAVED: INF_EXPENSE_LINE_NOT_SAVED,
    INF_SELECT_CREDIT_CARD_VENDOR: INF_SELECT_CREDIT_CARD_VENDOR,
    INF_SELECT_EXPENSE_TYPE: INF_SELECT_EXPENSE_TYPE,
    ERR_EXPENSE_TYPE_REQ: ERR_EXPENSE_TYPE_REQ,
    ERR_MILEAGE_ORIGIN_REQ: ERR_MILEAGE_ORIGIN_REQ,
    ERR_MILEAGE_DESTINATION_REQ: ERR_MILEAGE_DESTINATION_REQ,
    ERR_MILES_REQ: ERR_MILES_REQ
}