import COMMON_HELP from '@salesforce/label/c.COMMON_HELP';
import KNOWLEDGE_BASE from '@salesforce/label/c.KNOWLEDGE_BASE';
import COMMON_CANCEL from '@salesforce/label/c.COMMON_CANCEL';
import COMMON_CONFIRM from '@salesforce/label/c.COMMON_CONFIRM';
import CASH_RECEIPT_REFUND_ACCOUNTING_INFO_HEADER from '@salesforce/label/c.CASH_RECEIPT_REFUND_ACCOUNTING_INFO_HEADER';
export default {
    COMMON_HELP : COMMON_HELP,
    KNOWLEDGE_BASE : KNOWLEDGE_BASE,
    COMMON_CANCEL : COMMON_CANCEL,
    COMMON_CONFIRM : COMMON_CONFIRM,
    CASH_RECEIPT_REFUND_ACCOUNTING_INFO_HEADER
}