import ERR_PROJECT_TASK_RECEIVE_PROCESS from '@salesforce/label/c.ERR_PROJECT_TASK_RECEIVE_PROCESS';
import COMMON_PROJECT_IS_REQUIRED from '@salesforce/label/c.COMMON_PROJECT_IS_REQUIRED';
import COMMON_PROJECT_TASK from '@salesforce/label/c.COMMON_PROJECT_TASK';
import COMMON_SELECT_PROJECT_TASK from '@salesforce/label/c.COMMON_SELECT_PROJECT_TASK';
import COMMON_PROJECT_TASK_IS_REQUIRED from '@salesforce/label/c.COMMON_PROJECT_TASK_IS_REQUIRED';
export default {
    ERR_PROJECT_TASK_RECEIVE_PROCESS : ERR_PROJECT_TASK_RECEIVE_PROCESS,
    COMMON_PROJECT_IS_REQUIRED : COMMON_PROJECT_IS_REQUIRED,
    COMMON_PROJECT_TASK : COMMON_PROJECT_TASK,
    COMMON_SELECT_PROJECT_TASK : COMMON_SELECT_PROJECT_TASK,
    COMMON_PROJECT_TASK_IS_REQUIRED : COMMON_PROJECT_TASK_IS_REQUIRED
}