import ERR_EXPENSE_LINE_UPDATE_FAILED from '@salesforce/label/c.ERR_EXPENSE_LINE_UPDATE_FAILED';
import ERR_NO_EXPENSE_LINE_MILEAGE_LINE_EXIST from '@salesforce/label/c.ERR_NO_EXPENSE_LINE_MILEAGE_LINE_EXIST';
import INF_MILEAGE from '@salesforce/label/c.INF_MILEAGE';
import INF_DELETE_EXPENSE_LINE from '@salesforce/label/c.INF_DELETE_EXPENSE_LINE';
import WRN_DELETE_EXPENSE_LINE from '@salesforce/label/c.WRN_DELETE_EXPENSE_LINE';
import WRN_YOU_HAVE_UNSAVED_CHANGES from '@salesforce/label/c.WRN_YOU_HAVE_UNSAVED_CHANGES';
import COMMON_EXPENSES from '@salesforce/label/c.COMMON_EXPENSES';
import COMMON_MILEAGE from '@salesforce/label/c.COMMON_MILEAGE';

export default {
    ERR_EXPENSE_LINE_UPDATE_FAILED: ERR_EXPENSE_LINE_UPDATE_FAILED,
    ERR_NO_EXPENSE_LINE_MILEAGE_LINE_EXIST: ERR_NO_EXPENSE_LINE_MILEAGE_LINE_EXIST,
    INF_MILEAGE: INF_MILEAGE,
    INF_DELETE_EXPENSE_LINE: INF_DELETE_EXPENSE_LINE,
    WRN_DELETE_EXPENSE_LINE: WRN_DELETE_EXPENSE_LINE,
    WRN_YOU_HAVE_UNSAVED_CHANGES: WRN_YOU_HAVE_UNSAVED_CHANGES,
    COMMON_EXPENSES: COMMON_EXPENSES,
    COMMON_MILEAGE: COMMON_MILEAGE
}