import INF_SORT_ORDER_ROWS_NUMBER from '@salesforce/label/c.INF_SORT_ORDER_ROWS_NUMBER';
import INF_ADDED_TO_PARENT_LEDGER from '@salesforce/label/c.INF_ADDED_TO_PARENT_LEDGER';
import INF_ENTER_A_NO_BETWEEN_1_AND from '@salesforce/label/c.INF_ENTER_A_NO_BETWEEN_1_AND';
import INF_TO_CHANGE_THE_ORDER from '@salesforce/label/c.INF_TO_CHANGE_THE_ORDER';
import INF_PARENT from '@salesforce/label/c.INF_PARENT';
import INF_MODIFY_SORT_ORDER from '@salesforce/label/c.INF_MODIFY_SORT_ORDER';

export default {
    INF_SORT_ORDER_ROWS_NUMBER: INF_SORT_ORDER_ROWS_NUMBER,
    INF_ADDED_TO_PARENT_LEDGER: INF_ADDED_TO_PARENT_LEDGER,
    INF_ENTER_A_NO_BETWEEN_1_AND: INF_ENTER_A_NO_BETWEEN_1_AND,
    INF_TO_CHANGE_THE_ORDER: INF_TO_CHANGE_THE_ORDER,
    INF_PARENT: INF_PARENT,
    INF_MODIFY_SORT_ORDER: INF_MODIFY_SORT_ORDER
}