import RESET_LDO_SOURCE_DOCUMENT_INTERIM_POSTING_STATUS from '@salesforce/label/c.RESET_LDO_SOURCE_DOCUMENT_INTERIM_POSTING_STATUS';
import RESET_LDO_SOURCE_DOCUMENT_INTERIM_POSTING_STATUS_HELPTEXT from '@salesforce/label/c.RESET_LDO_SOURCE_DOCUMENT_INTERIM_POSTING_STATUS_HELPTEXT';
import COMMON_RESET from '@salesforce/label/c.COMMON_RESET';
export default {
    RESET_LDO_SOURCE_DOCUMENT_INTERIM_POSTING_STATUS : RESET_LDO_SOURCE_DOCUMENT_INTERIM_POSTING_STATUS,
    RESET_LDO_SOURCE_DOCUMENT_INTERIM_POSTING_STATUS_HELPTEXT : RESET_LDO_SOURCE_DOCUMENT_INTERIM_POSTING_STATUS_HELPTEXT,
    COMMON_RESET : COMMON_RESET
    
}