import INF_SHIPPING_STREET from '@salesforce/label/c.INF_SHIPPING_STREET';
import INF_VALIDATED_SHIPPING_STREET from '@salesforce/label/c.INF_VALIDATED_SHIPPING_STREET';
import INF_SHIPPING_CITY from '@salesforce/label/c.INF_SHIPPING_CITY';
import INF_VALIDATED_SHIPPING_CITY from '@salesforce/label/c.INF_VALIDATED_SHIPPING_CITY';
import INF_SHIPPING_STATE from '@salesforce/label/c.INF_SHIPPING_STATE';
import INF_VALIDATED_SHIPPING_STATE from '@salesforce/label/c.INF_VALIDATED_SHIPPING_STATE';
import INF_SHIPPING_POSTAL_CODE from '@salesforce/label/c.INF_SHIPPING_POSTAL_CODE';
import INF_VALIDATED_SHIPPING_POSTAL_CODE from '@salesforce/label/c.INF_VALIDATED_SHIPPING_POSTAL_CODE';
import INF_SHIPPING_COUNTRY from '@salesforce/label/c.INF_SHIPPING_COUNTRY';
import INF_VALIDATED_SHIPPING_COUNTRY from '@salesforce/label/c.INF_VALIDATED_SHIPPING_COUNTRY';
import INF_BILLING_STREET from '@salesforce/label/c.INF_BILLING_STREET';
import INF_VALIDATED_BILLING_STREET from '@salesforce/label/c.INF_VALIDATED_BILLING_STREET';
import INF_BILLING_CITY from '@salesforce/label/c.INF_BILLING_CITY';
import INF_VALIDATED_BILLING_CITY from '@salesforce/label/c.INF_VALIDATED_BILLING_CITY';
import INF_BILLING_STATE from '@salesforce/label/c.INF_BILLING_STATE';
import INF_VALIDATED_BILLING_STATE from '@salesforce/label/c.INF_VALIDATED_BILLING_STATE';
import INF_BILLING_POSTAL_CODE from '@salesforce/label/c.INF_BILLING_POSTAL_CODE';
import INF_VALIDATED_BILLING_POSTAL_CODE from '@salesforce/label/c.INF_VALIDATED_BILLING_POSTAL_CODE';
import INF_BILLING_COUNTRY from '@salesforce/label/c.INF_BILLING_COUNTRY';
import INF_VALIDATED_BILLING_COUNTRY from '@salesforce/label/c.INF_VALIDATED_BILLING_COUNTRY';
import ERR_NOT_AUTHENTICATE_ACCOUNT_AVALARA_SERVICE from '@salesforce/label/c.ERR_NOT_AUTHENTICATE_ACCOUNT_AVALARA_SERVICE';
import INF_SUCCESSFULLY_UPDATED from '@salesforce/label/c.INF_SUCCESSFULLY_UPDATED';
import INF_AVALARA_LICENSE from '@salesforce/label/c.INF_AVALARA_LICENSE';

export default {
    INF_SHIPPING_STREET: INF_SHIPPING_STREET,
    INF_VALIDATED_SHIPPING_STREET: INF_VALIDATED_SHIPPING_STREET,
    INF_SHIPPING_CITY: INF_SHIPPING_CITY,
    INF_VALIDATED_SHIPPING_CITY: INF_VALIDATED_SHIPPING_CITY,
    INF_SHIPPING_STATE: INF_SHIPPING_STATE,
    INF_VALIDATED_SHIPPING_STATE: INF_VALIDATED_SHIPPING_STATE,
    INF_SHIPPING_POSTAL_CODE: INF_SHIPPING_POSTAL_CODE,
    INF_VALIDATED_SHIPPING_POSTAL_CODE: INF_VALIDATED_SHIPPING_POSTAL_CODE,
    INF_SHIPPING_COUNTRY: INF_SHIPPING_COUNTRY,
    INF_VALIDATED_SHIPPING_COUNTRY: INF_VALIDATED_SHIPPING_COUNTRY,
    INF_BILLING_STREET: INF_BILLING_STREET,
    INF_VALIDATED_BILLING_STREET: INF_VALIDATED_BILLING_STREET,
    INF_BILLING_CITY: INF_BILLING_CITY,
    INF_VALIDATED_BILLING_CITY: INF_VALIDATED_BILLING_CITY,
    INF_BILLING_STATE: INF_BILLING_STATE,
    INF_VALIDATED_BILLING_STATE: INF_VALIDATED_BILLING_STATE,
    INF_BILLING_POSTAL_CODE: INF_BILLING_POSTAL_CODE,
    INF_VALIDATED_BILLING_POSTAL_CODE: INF_VALIDATED_BILLING_POSTAL_CODE,
    INF_BILLING_COUNTRY: INF_BILLING_COUNTRY,
    INF_VALIDATED_BILLING_COUNTRY: INF_VALIDATED_BILLING_COUNTRY,
    ERR_NOT_AUTHENTICATE_ACCOUNT_AVALARA_SERVICE: ERR_NOT_AUTHENTICATE_ACCOUNT_AVALARA_SERVICE,
    INF_SUCCESSFULLY_UPDATED: INF_SUCCESSFULLY_UPDATED,
    INF_AVALARA_LICENSE: INF_AVALARA_LICENSE
}