import INF_CLONE_REPORT from '@salesforce/label/c.INF_CLONE_REPORT';
import INF_CLONE_REPORT_NAME from '@salesforce/label/c.INF_CLONE_REPORT_NAME';
import INF_CLONE_REPORT_DESCRIPTION from '@salesforce/label/c.INF_CLONE_REPORT_DESCRIPTION';
import INF_CLONE_AS_CUSTOM from '@salesforce/label/c.INF_CLONE_AS_CUSTOM';
import INF_COMPANY_NAME from '@salesforce/label/c.INF_COMPANY_NAME';
import INF_MORE_INFORMATION from '@salesforce/label/c.INF_MORE_INFORMATION';
import INF_COMPLETED_DATE_OR_TIME from '@salesforce/label/c.INF_COMPLETED_DATE_OR_TIME';
import INF_RERUN from '@salesforce/label/c.INF_RERUN';
import INF_CLONE_REPORT_DEFINITION_CUSTOM_REPORT from '@salesforce/label/c.INF_CLONE_REPORT_DEFINITION_CUSTOM_REPORT';
import INF_SUBTITLE_HERE from '@salesforce/label/c.INF_SUBTITLE_HERE';
import INF_ROUNDED_TO_1000s from '@salesforce/label/c.INF_ROUNDED_TO_1000s';
import INF_ROUNDED_TO_WHOLE_AMOUNTS from '@salesforce/label/c.INF_ROUNDED_TO_WHOLE_AMOUNTS';
import XCSV from '@salesforce/label/c.XCSV';

export default {
    INF_CLONE_REPORT: INF_CLONE_REPORT,
    INF_CLONE_REPORT_NAME: INF_CLONE_REPORT_NAME,
    INF_CLONE_REPORT_DESCRIPTION: INF_CLONE_REPORT_DESCRIPTION,
    INF_CLONE_AS_CUSTOM: INF_CLONE_AS_CUSTOM,
    INF_COMPANY_NAME: INF_COMPANY_NAME,
    INF_MORE_INFORMATION: INF_MORE_INFORMATION,
    INF_COMPLETED_DATE_OR_TIME: INF_COMPLETED_DATE_OR_TIME,
    INF_RERUN: INF_RERUN,
    INF_CLONE_REPORT_DEFINITION_CUSTOM_REPORT: INF_CLONE_REPORT_DEFINITION_CUSTOM_REPORT,
    INF_SUBTITLE_HERE: INF_SUBTITLE_HERE,
    INF_ROUNDED_TO_1000s: INF_ROUNDED_TO_1000s,
    INF_ROUNDED_TO_WHOLE_AMOUNTS: INF_ROUNDED_TO_WHOLE_AMOUNTS,
    XCSV: XCSV
}