import WRN_ARE_YOU_SURE_LOADING from '@salesforce/label/c.WRN_ARE_YOU_SURE_LOADING';
import INF_PLEASE_CONFIRM_FOR_PERIOD from '@salesforce/label/c.INF_PLEASE_CONFIRM_FOR_PERIOD';

export default {
    WRN_ARE_YOU_SURE_LOADING: WRN_ARE_YOU_SURE_LOADING,
    INF_PLEASE_CONFIRM_FOR_PERIOD: INF_PLEASE_CONFIRM_FOR_PERIOD
}