import INF_FILTER_BY_BILLING_AMOUNT from '@salesforce/label/c.INF_FILTER_BY_BILLING_AMOUNT';
import INF_BILLING_DATE_RANGE from '@salesforce/label/c.INF_BILLING_DATE_RANGE';
import INF_BILLING_DATE_START from '@salesforce/label/c.INF_BILLING_DATE_START';
import INF_BILLING_DATE_END from '@salesforce/label/c.INF_BILLING_DATE_END';

export default {
    INF_FILTER_BY_BILLING_AMOUNT: INF_FILTER_BY_BILLING_AMOUNT,
    INF_BILLING_DATE_RANGE: INF_BILLING_DATE_RANGE,
    INF_BILLING_DATE_START: INF_BILLING_DATE_START,
    INF_BILLING_DATE_END: INF_BILLING_DATE_END
}