//DO NOT CHANGE THE COMMENT STYLE IN THIS CLASS FOR THE DEPRECATED ANNOTATION!
/* 
@Deprecated
*/
global with sharing class CashDisbursementService {
    /*
    @Deprecated
    */
    global static List<PostResult> postCashDisbursements(List<Cash_Disbursement__c> cashDisbursements) {
        return null;
    }
    /*
    @Deprecated
    */
    global static List<PostResult> unpostCashDisbursements(List<Cash_Disbursement__c> cashDisbursements) {
       return null;
    }
}