import INF_LEARN_MORE_ABOUT_ACCOUNTING_SEED from '@salesforce/label/c.INF_LEARN_MORE_ABOUT_ACCOUNTING_SEED';
import KNOWLEDGE_BASE from '@salesforce/label/c.KNOWLEDGE_BASE';
export default {
    INF_LEARN_MORE_ABOUT_ACCOUNTING_SEED : INF_LEARN_MORE_ABOUT_ACCOUNTING_SEED,
    KNOWLEDGE_BASE : KNOWLEDGE_BASE
}