import INF_RECORDS_SUCCESSFULLY_CREATED from '@salesforce/label/c.INF_RECORDS_SUCCESSFULLY_CREATED';
import COMMON_SELECT_LEDGER from '@salesforce/label/c.COMMON_SELECT_LEDGER';
import COMMON_DEPARTMENT from '@salesforce/label/c.COMMON_DEPARTMENT';
import INF_NO_EXISTS_GL_VARIABLE_FOR_DEPARTMENT_COLUMN from '@salesforce/label/c.INF_NO_EXISTS_GL_VARIABLE_FOR_DEPARTMENT_COLUMN';
import COMMON_CSV_FILE from '@salesforce/label/c.COMMON_CSV_FILE';
import COMMON_CREATE_RECORDS from '@salesforce/label/c.COMMON_CREATE_RECORDS';
export default {
    INF_RECORDS_SUCCESSFULLY_CREATED : INF_RECORDS_SUCCESSFULLY_CREATED,
    COMMON_SELECT_LEDGER : COMMON_SELECT_LEDGER,
    COMMON_DEPARTMENT : COMMON_DEPARTMENT,
    INF_NO_EXISTS_GL_VARIABLE_FOR_DEPARTMENT_COLUMN : INF_NO_EXISTS_GL_VARIABLE_FOR_DEPARTMENT_COLUMN,
    COMMON_CSV_FILE : COMMON_CSV_FILE,
    COMMON_CREATE_RECORDS: COMMON_CREATE_RECORDS
}