import INF_CLEARED_ONLY from '@salesforce/label/c.INF_CLEARED_ONLY';
import INF_UNCLEARED_ONLY from '@salesforce/label/c.INF_UNCLEARED_ONLY';
import ERR_FILTER_BY_TYPE_FOR_AMOUNT_FILTER from '@salesforce/label/c.ERR_FILTER_BY_TYPE_FOR_AMOUNT_FILTER';
import INF_SEARCH_BY_OPTIONS from '@salesforce/label/c.INF_SEARCH_BY_OPTIONS';
import INF_CLEARED_UNCLEARED from '@salesforce/label/c.INF_CLEARED_UNCLEARED';
import INF_SELECT_ONE from '@salesforce/label/c.INF_SELECT_ONE';
import INF_MIN from '@salesforce/label/c.INF_MIN';
import INF_MAX from '@salesforce/label/c.INF_MAX';
import INF_SEARCH_KEY from '@salesforce/label/c.INF_SEARCH_KEY';
import INF_AMOUNT_SMALL_MIN from '@salesforce/label/c.INF_AMOUNT_SMALL_MIN';
import INF_AMOUNT_SMALL_MAX from '@salesforce/label/c.INF_AMOUNT_SMALL_MAX';

export default {
    INF_CLEARED_ONLY: INF_CLEARED_ONLY,
    INF_UNCLEARED_ONLY: INF_UNCLEARED_ONLY,
    ERR_FILTER_BY_TYPE_FOR_AMOUNT_FILTER: ERR_FILTER_BY_TYPE_FOR_AMOUNT_FILTER,
    INF_SEARCH_BY_OPTIONS: INF_SEARCH_BY_OPTIONS,
    INF_CLEARED_UNCLEARED: INF_CLEARED_UNCLEARED,
    INF_SELECT_ONE: INF_SELECT_ONE,
    INF_MIN: INF_MIN,
    INF_MAX: INF_MAX,
    INF_SEARCH_KEY: INF_SEARCH_KEY,
    INF_AMOUNT_SMALL_MIN: INF_AMOUNT_SMALL_MIN,
    INF_AMOUNT_SMALL_MAX: INF_AMOUNT_SMALL_MAX
}