var CARD_NUMBER_IFIELD_NAME="card-number",CVV_IFIELD_NAME="cvv",cardFrameLoaded=!1,cvvFrameLoaded=!1,cardTokenRecieved=!1,cvvTokenRecieved=!1,tokensReceived=!1,latestErrorTime=new Date,cachedIFieldStyles={},cachedAccountxKey="",cachedAccountSoftwareName="",cachedAccountSoftwareVersion="",cardNumKeyPressCallbacks=[],cvvKeyPressCallbacks=[];function getByCustomAttribute(b,a){return document.querySelector("["+b+"='"+a+"']")}
window.addEventListener("message",function(b){var a=b.data;if("loaded"===a.action){console.log("Message received: ifield loaded");a=document.getElementsByTagName("iframe");for(var c=0;c<a.length;c++)if(a[c].contentWindow==b.source){var d=a[c].getAttribute("data-ifields-id");var e=a[c].getAttribute("data-ifields-placeholder");break}console.log("Loaded ifield id: "+d);for(var f in cachedIFieldStyles)setIfieldStyle(f,cachedIFieldStyles[f]);setAccount(cachedAccountxKey,cachedAccountSoftwareName,cachedAccountSoftwareVersion);
"card-number"===d?(b.source.postMessage({action:"init",tokenType:"card"},"*"),setPlaceholder(d,e),cardFrameLoaded=!0):"cvv"===d&&(b.source.postMessage({action:"init",tokenType:"cvv"},"*"),setPlaceholder(d,e),cvvFrameLoaded=!0)}else if("token"===a.action)console.log("Message recived: token"),"error"===a.data.result?(latestErrorTime=new Date,getByCustomAttribute("data-ifields-id","card-data-error").innerHTML=a.data.errorMessage):"card"===a.data.xTokenType?(getByCustomAttribute("data-ifields-id","card-number-token").value=
a.data.xToken,cardTokenRecieved=!0):"cvv"===a.data.xTokenType&&(getByCustomAttribute("data-ifields-id","cvv-token").value=a.data.xToken,cvvTokenRecieved=!0);else if("update"===a.action){if("card"===a.xTokenType){b={action:"updateIssuer",issuer:a.data.issuer};iFieldElementExists("cvv")&&getByCustomAttribute("data-ifields-id","cvv").contentWindow.postMessage(b,"*");var g=cardNumKeyPressCallbacks}else"cvv"===a.xTokenType&&(g=cvvKeyPressCallbacks);for(c=0;c<g.length;c++)g[c](a.data)}},!1);
function iFieldElementExists(b){return"undefined"!==typeof getByCustomAttribute("data-ifields-id",b)}
function getTokens(b,a,c){if(null===c||void 0===c||isNaN(c)||0>=c)c=6E4;void 0===b&&(b=Function.prototype);void 0===a&&(a=Function.prototype);cvvTokenRecieved=cardTokenRecieved=!1;getByCustomAttribute("data-ifields-id","card-number-token").value="";getByCustomAttribute("data-ifields-id","cvv-token").value="";getByCustomAttribute("data-ifields-id","card-data-error").innerHTML="";tokensReceived=!1;var d={action:"getToken"};if(iFieldElementExists("card-number"))var e=setInterval(function(){cardFrameLoaded&&
(clearInterval(e),getByCustomAttribute("data-ifields-id","card-number").contentWindow.postMessage(d,"*"))},100);if(iFieldElementExists("cvv"))var f=setInterval(function(){cvvFrameLoaded&&(clearInterval(f),getByCustomAttribute("data-ifields-id","cvv").contentWindow.postMessage(d,"*"))},100);var g=iFieldElementExists("card-number"),m=iFieldElementExists("cvv"),h=setInterval(function(){0!=g&&!cardTokenRecieved||0!=m&&!cvvTokenRecieved||(clearInterval(h),tokensReceived=!0,getByCustomAttribute("data-ifields-id",
"card-data-error").innerHTML="",b())},100),l=(new Date).getTime(),k=setInterval(function(){var b=(new Date).getTime();l<latestErrorTime?(clearInterval(e),clearInterval(f),clearInterval(k),clearInterval(h),a()):tokensReceived?clearInterval(k):b-l>c&&(clearInterval(e),clearInterval(f),clearInterval(k),clearInterval(h),getByCustomAttribute("data-ifields-id","card-data-error").innerHTML="Transaction timed out",a())},100)}
function clearIfield(b){console.log("Clearing ifield data for iframe id "+b);getByCustomAttribute("data-ifields-id",b).contentWindow.postMessage({action:"clearData"},"*")}
function setIfieldStyle(b,a){cachedIFieldStyles[b]=a;var c=setInterval(function(){if(iFieldElementExists(b)&&("card-number"===b&&cardFrameLoaded||"cvv"===b&&cvvFrameLoaded)){clearInterval(c);var d={action:"style",data:a};console.log("Setting ifield style for iframe id "+b);getByCustomAttribute("data-ifields-id",b).contentWindow.postMessage(d,"*")}},100)}
function setPlaceholder(b,a){a={action:"setPlaceholder",data:a};console.log("Setting ifield placeholder for iframe id "+b);getByCustomAttribute("data-ifields-id",b).contentWindow.postMessage(a,"*")}
function setAccount(b,a,c){cachedAccountxKey=b;cachedAccountSoftwareName=a;cachedAccountSoftwareVersion=c;var d={action:"setAccountData",data:{xKey:b,xSoftwareName:a,xSoftwareVersion:c}};if(iFieldElementExists("card-number"))var e=setInterval(function(){cardFrameLoaded&&(clearInterval(e),console.log("Setting ifield account data for iframe id card-number"),getByCustomAttribute("data-ifields-id","card-number").contentWindow.postMessage(d,"*"))},100);if(iFieldElementExists("cvv"))var f=setInterval(function(){cvvFrameLoaded&&
(clearInterval(f),console.log("Setting ifield account data for iframe id cvv"),getByCustomAttribute("data-ifields-id","cvv").contentWindow.postMessage(d,"*"))},100)}function addIfieldKeyPressCallback(b,a){b===CARD_NUMBER_IFIELD_NAME?cardNumKeyPressCallbacks.push(a):b===CVV_IFIELD_NAME&&cvvKeyPressCallbacks.push(a)}function focusIfield(b){var a={action:"focus"};iFieldElementExists(b)&&getByCustomAttribute("data-ifields-id",b).contentWindow.postMessage(a,"*")}
function enableAutoFormatting(b){var a={action:"format",data:{formatChar:b||" "}};if(iFieldElementExists("card-number"))var c=setInterval(function(){cardFrameLoaded&&(clearInterval(c),getByCustomAttribute("data-ifields-id","card-number").contentWindow.postMessage(a,"*"))},100)};
