import WRN_CONFIGURATION_REQUIRED from '@salesforce/label/c.WRN_CONFIGURATION_REQUIRED';
import INF_KB_ARTICLE_COMPLETE_SETUP from '@salesforce/label/c.INF_KB_ARTICLE_COMPLETE_SETUP';
import INF_DATE_OR_TIME_CLOSED from '@salesforce/label/c.INF_DATE_OR_TIME_CLOSED';
import INF_NO_HIERARCHIES_TO_DISPLAY from '@salesforce/label/c.INF_NO_HIERARCHIES_TO_DISPLAY';
import INF_RUN_FOR_PARENT_CONSIDERATIONS from '@salesforce/label/c.INF_RUN_FOR_PARENT_CONSIDERATIONS';
import INF_RUN_PARENT_CONSIDERATIONS_WITH_CHILDREN from '@salesforce/label/c.INF_RUN_PARENT_CONSIDERATIONS_WITH_CHILDREN';
import INF_LAST_PERIOD from '@salesforce/label/c.INF_LAST_PERIOD';
import INF_LAST_RUN from '@salesforce/label/c.INF_LAST_RUN';
import INF_GENERATED_BY from '@salesforce/label/c.INF_GENERATED_BY';
import INF_PAGE_REFRESHED from '@salesforce/label/c.INF_PAGE_REFRESHED';
import INF_CONSIDERATIONS_ROUTINE_RUN_FOR from '@salesforce/label/c.INF_CONSIDERATIONS_ROUTINE_RUN_FOR';
import INF_REFRESH_PAGE_UPDATES from '@salesforce/label/c.INF_REFRESH_PAGE_UPDATES';
import INF_CONSOLIDATION_CONFIGURATION from '@salesforce/label/c.INF_CONSOLIDATION_CONFIGURATION';

export default {
    WRN_CONFIGURATION_REQUIRED: WRN_CONFIGURATION_REQUIRED,
    INF_KB_ARTICLE_COMPLETE_SETUP: INF_KB_ARTICLE_COMPLETE_SETUP,
    INF_DATE_OR_TIME_CLOSED: INF_DATE_OR_TIME_CLOSED,
    INF_NO_HIERARCHIES_TO_DISPLAY: INF_NO_HIERARCHIES_TO_DISPLAY,
    INF_RUN_FOR_PARENT_CONSIDERATIONS: INF_RUN_FOR_PARENT_CONSIDERATIONS,
    INF_RUN_PARENT_CONSIDERATIONS_WITH_CHILDREN: INF_RUN_PARENT_CONSIDERATIONS_WITH_CHILDREN,
    INF_LAST_PERIOD: INF_LAST_PERIOD,
    INF_LAST_RUN: INF_LAST_RUN,
    INF_GENERATED_BY: INF_GENERATED_BY,
    INF_PAGE_REFRESHED: INF_PAGE_REFRESHED,
    INF_CONSIDERATIONS_ROUTINE_RUN_FOR: INF_CONSIDERATIONS_ROUTINE_RUN_FOR,
    INF_REFRESH_PAGE_UPDATES: INF_REFRESH_PAGE_UPDATES,
    INF_CONSOLIDATION_CONFIGURATION: INF_CONSOLIDATION_CONFIGURATION
}