import COMMON_ALL_LABEL from '@salesforce/label/c.COMMON_ALL';
import CASH_DISBURSEMENT_LABEL from '@salesforce/label/c.COMMON_CASH_DISBURSEMENT';
import JOURNAL_ENTRY_LINE_TYPE_LABEL from '@salesforce/label/c.COMMON_JOURNAL_ENTRY_LINE';
import ERR_IN_BANK_DISBURSEMENT_MANAGER_COMPONENT from '@salesforce/label/c.ERR_IN_BANK_DISBURSEMENT_MANAGER_COMPONENT';
import NO_MATCHING_RECORD_FOUND from '@salesforce/label/c.NO_MATCHING_RECORD_FOUND';
import BANK_DISBURSEMENT_SEARCH_FIELDSET from '@salesforce/label/c.BANK_DISBURSEMENT_SEARCH_FIELDSET';
import ERR_FETCHING_BANKDIS_RECORD from '@salesforce/label/c.ERR_FETCHING_BANKDIS_RECORD';
import HEADER_FOR_BANK_DISBURSEMENT_MANAGER_LWC from '@salesforce/label/c.HEADER_FOR_BANK_DISBURSEMENT_MANAGER_LWC';
import commonLoading from '@salesforce/label/c.COMMON_LOADING';
import COMMON_ASSOCIATE from '@salesforce/label/c.COMMON_ASSOCIATE';
import COMMON_UNASSOCIATE from '@salesforce/label/c.COMMON_UNASSOCIATE';
import AUTOMATED_JOBS_SCHEDULED_JOBS_START_DATE from '@salesforce/label/c.AUTOMATED_JOBS_SCHEDULED_JOBS_START_DATE';
import COMMON_END_DATE from '@salesforce/label/c.COMMON_END_DATE';
import COMMON_TYPE from '@salesforce/label/c.COMMON_TYPE';
import COMMON_AMOUNT from '@salesforce/label/c.COMMON_AMOUNT';
import TAB_HEADER_FOR_ASSOCIATED_RECORDS_BANK_DIS_LWC from '@salesforce/label/c.TAB_HEADER_FOR_ASSOCIATED_RECORDS_BANK_DIS_LWC';
import TAB_HEADER_FOR_UNASSOCIATED_RECORDS_BANK_DIS_LWC from '@salesforce/label/c.TAB_HEADER_FOR_UNASSOCIATED_RECORDS_BANK_DIS_LWC';
import COMMON_NAME from '@salesforce/label/c.COMMON_NAME';
import COMMON_VENDOR from '@salesforce/label/c.COMMON_VENDOR';
import RECORD_DATE_COL_FOR_BANKDISB_LWC from '@salesforce/label/c.RECORD_DATE_COL_FOR_BANKDISB_LWC';
import INF_LEDGER_AMOUNT from '@salesforce/label/c.INF_LEDGER_AMOUNT';
import COMMON_VIEW from '@salesforce/label/c.COMMON_VIEW';
import COMMON_REFERENCE from '@salesforce/label/c.COMMON_REFERENCE';
import SUCCESS_MSG_AFTER_ASSOCIATED_RECS_ON_BANKDISB_LWC from '@salesforce/label/c.SUCCESS_MSG_AFTER_ASSOCIATED_RECS_ON_BANKDISB_LWC';
import SUCCESS_MSG_AFTER_UNASSOCIATED_RECS_ON_BANKDISB_LWC from '@salesforce/label/c.SUCCESS_MSG_AFTER_UNASSOCIATED_RECS_ON_BANKDISB_LWC';
import BANK_DISB_AMOUNT_HEADING_FOR_BANKDISB_MANAGER_LWC from '@salesforce/label/c.BANK_DISB_AMOUNT_HEADING_FOR_BANKDISB_MANAGER_LWC';
import FILTER_RESULTS_HEADER from '@salesforce/label/c.FILTER_RESULTS_HEADER';
import INFO_NO_RECORD_MSG from '@salesforce/label/c.INFO_NO_RECORD_MSG';
import NO_RECORDS_FOUND_LABEL_FOR_BANKDIS_MANAGER from '@salesforce/label/c.NO_RECORDS_FOUND_LABEL_FOR_BANKDIS_MANAGER';
import COMMON_BANK_DISBURSEMENT from '@salesforce/label/c.COMMON_BANK_DISBURSEMENT';
import ERR_PREVENT_ASSOCIATING_RECORD_IF_BANK_RECONCILIATION_CLEARED from '@salesforce/label/c.ERR_PREVENT_ASSOCIATING_RECORD_IF_BANK_RECONCILIATION_CLEARED';
import ERR_BANK_DISB_LWC_COMP_IF_AMOUNT_EXCEEDS from '@salesforce/label/c.ERR_BANK_DISB_LWC_COMP_IF_AMOUNT_EXCEEDS';

export const bankDisbursementLabels = () => {
    return {
        COMMON_ALL_LABEL,
        CASH_DISBURSEMENT_LABEL,
        JOURNAL_ENTRY_LINE_TYPE_LABEL,
        ERR_IN_BANK_DISBURSEMENT_MANAGER_COMPONENT,
        NO_MATCHING_RECORD_FOUND,
        BANK_DISBURSEMENT_SEARCH_FIELDSET,
        ERR_FETCHING_BANKDIS_RECORD,
        HEADER_FOR_BANK_DISBURSEMENT_MANAGER_LWC,
        commonLoading,
        COMMON_ASSOCIATE,
        COMMON_UNASSOCIATE,
        AUTOMATED_JOBS_SCHEDULED_JOBS_START_DATE,
        COMMON_END_DATE,
        COMMON_TYPE,
        COMMON_AMOUNT,
        TAB_HEADER_FOR_ASSOCIATED_RECORDS_BANK_DIS_LWC,
        TAB_HEADER_FOR_UNASSOCIATED_RECORDS_BANK_DIS_LWC,
        COMMON_NAME,
        COMMON_VENDOR,
        RECORD_DATE_COL_FOR_BANKDISB_LWC,
        COMMON_VIEW,
        COMMON_REFERENCE,
        INF_LEDGER_AMOUNT,
        SUCCESS_MSG_AFTER_ASSOCIATED_RECS_ON_BANKDISB_LWC,
        SUCCESS_MSG_AFTER_UNASSOCIATED_RECS_ON_BANKDISB_LWC,
        BANK_DISB_AMOUNT_HEADING_FOR_BANKDISB_MANAGER_LWC,
        FILTER_RESULTS_HEADER,
        INFO_NO_RECORD_MSG,
        NO_RECORDS_FOUND_LABEL_FOR_BANKDIS_MANAGER,
        COMMON_BANK_DISBURSEMENT,
        ERR_PREVENT_ASSOCIATING_RECORD_IF_BANK_RECONCILIATION_CLEARED,
        ERR_BANK_DISB_LWC_COMP_IF_AMOUNT_EXCEEDS
    }
}