import INF_SELECT_TYPE_FILTER_REPORT from '@salesforce/label/c.INF_SELECT_TYPE_FILTER_REPORT';
import INF_AGGREGATE_REPORT_PICKLIST_SELECTION from '@salesforce/label/c.INF_AGGREGATE_REPORT_PICKLIST_SELECTION';
import INF_AMORTIZATION_ENTRY from '@salesforce/label/c.INF_AMORTIZATION_ENTRY';
import INF_AP_DISBURSEMENT from '@salesforce/label/c.INF_AP_DISBURSEMENT';
import COMMON_BILLING_CASH_RECEIPT from '@salesforce/label/c.COMMON_BILLING_CASH_RECEIPT';
import INF_TIME_CARD_DAY from '@salesforce/label/c.INF_TIME_CARD_DAY';
import INF_INBOUND_INV_MVMT from '@salesforce/label/c.INF_INBOUND_INV_MVMT';
import INF_MANUFACTURING_INV_MVMT from '@salesforce/label/c.INF_MANUFACTURING_INV_MVMT';
import INF_OUTBOUND_INV_MVMT from '@salesforce/label/c.INF_OUTBOUND_INV_MVMT';
import INF_PURCHASE_ORDER_INV_MVMT from '@salesforce/label/c.INF_PURCHASE_ORDER_INV_MVMT';
import INF_SALES_ORDER_INV_MVMT from '@salesforce/label/c.INF_SALES_ORDER_INV_MVMT';
import INF_ACCOUNTS from '@salesforce/label/c.INF_ACCOUNTS';
import INF_RESULTS_LOADING_ON_TRANSACTIONS from '@salesforce/label/c.INF_RESULTS_LOADING_ON_TRANSACTIONS';
import INF_SCROLL_DOWN_VIEW_TRANSACTIONS from '@salesforce/label/c.INF_SCROLL_DOWN_VIEW_TRANSACTIONS';

export default {
    INF_SELECT_TYPE_FILTER_REPORT: INF_SELECT_TYPE_FILTER_REPORT,
    INF_AGGREGATE_REPORT_PICKLIST_SELECTION: INF_AGGREGATE_REPORT_PICKLIST_SELECTION,
    INF_AMORTIZATION_ENTRY: INF_AMORTIZATION_ENTRY,
    INF_AP_DISBURSEMENT: INF_AP_DISBURSEMENT,
    COMMON_BILLING_CASH_RECEIPT: COMMON_BILLING_CASH_RECEIPT,
    INF_TIME_CARD_DAY: INF_TIME_CARD_DAY,
    INF_INBOUND_INV_MVMT: INF_INBOUND_INV_MVMT,
    INF_MANUFACTURING_INV_MVMT: INF_MANUFACTURING_INV_MVMT,
    INF_OUTBOUND_INV_MVMT: INF_OUTBOUND_INV_MVMT,
    INF_PURCHASE_ORDER_INV_MVMT: INF_PURCHASE_ORDER_INV_MVMT,
    INF_SALES_ORDER_INV_MVMT: INF_SALES_ORDER_INV_MVMT,
    INF_ACCOUNTS: INF_ACCOUNTS,
    INF_RESULTS_LOADING_ON_TRANSACTIONS: INF_RESULTS_LOADING_ON_TRANSACTIONS,
    INF_SCROLL_DOWN_VIEW_TRANSACTIONS: INF_SCROLL_DOWN_VIEW_TRANSACTIONS
}