import INF_BANK_RULE_NAME from '@salesforce/label/c.INF_BANK_RULE_NAME';
import INF_PRIORITY_ORDER from '@salesforce/label/c.INF_PRIORITY_ORDER';
import INF_BANK_RULE_SUCCESSFULLY_SAVED from '@salesforce/label/c.INF_BANK_RULE_SUCCESSFULLY_SAVED';
import INF_RECORD_SUCCESSFULLY_DELETED from '@salesforce/label/c.INF_RECORD_SUCCESSFULLY_DELETED';
import INF_BANK_RULE from '@salesforce/label/c.INF_BANK_RULE';
import INF_CREATE_A_NEW_RULE from '@salesforce/label/c.INF_CREATE_A_NEW_RULE';

export default {
    INF_BANK_RULE_NAME: INF_BANK_RULE_NAME,
    INF_PRIORITY_ORDER: INF_PRIORITY_ORDER,
    INF_BANK_RULE_SUCCESSFULLY_SAVED: INF_BANK_RULE_SUCCESSFULLY_SAVED,
    INF_RECORD_SUCCESSFULLY_DELETED: INF_RECORD_SUCCESSFULLY_DELETED,
    INF_BANK_RULE: INF_BANK_RULE,
    INF_CREATE_A_NEW_RULE: INF_CREATE_A_NEW_RULE
}