import ERR_PUBSUB_LISTENER_NEEDS_PAGEREF_PROPERTY from '@salesforce/label/c.ERR_PUBSUB_LISTENER_NEEDS_PAGEREF_PROPERTY';
export default {
    ERR_PUBSUB_LISTENER_NEEDS_PAGEREF_PROPERTY : ERR_PUBSUB_LISTENER_NEEDS_PAGEREF_PROPERTY
}