import INF_DUPLICATE_ACCOUNTING_PERIOD_MSG from '@salesforce/label/c.INF_DUPLICATE_ACCOUNTING_PERIOD_MSG';
import INF_DUPLICATE_NAME_LOGO_MSG from '@salesforce/label/c.INF_DUPLICATE_NAME_LOGO_MSG';
import INF_EXPAND_REPORT_ROWS_MSG from '@salesforce/label/c.INF_EXPAND_REPORT_ROWS_MSG';
import INF_ROUNDING_HELP from '@salesforce/label/c.INF_ROUNDING_HELP';
import ERR_VALUE_REQ_SAVE_SETTINGS from '@salesforce/label/c.ERR_VALUE_REQ_SAVE_SETTINGS';
import INF_REPORT_DISPLAY from '@salesforce/label/c.INF_REPORT_DISPLAY';
import COMMON_SELECT_LEDGER from '@salesforce/label/c.COMMON_SELECT_LEDGER';
import INF_COMPANY_NAME_LOGO from '@salesforce/label/c.INF_COMPANY_NAME_LOGO';
import INF_COMPANY_NAME from '@salesforce/label/c.INF_COMPANY_NAME';
import INF_LOGO from '@salesforce/label/c.INF_LOGO';
import INF_DIEMENSION_CONSTRAINTS from '@salesforce/label/c.INF_DIEMENSION_CONSTRAINTS';
import INF_ACTUAL_SIZE_PREVIEW from '@salesforce/label/c.INF_ACTUAL_SIZE_PREVIEW';
import INF_DUPLICATE_ON_ALL_LEDGERS from '@salesforce/label/c.INF_DUPLICATE_ON_ALL_LEDGERS';
import INF_COLUMN_HEADER_FOR_PERIOD_NAME from '@salesforce/label/c.INF_COLUMN_HEADER_FOR_PERIOD_NAME';
import INF_DISPLAY_ON_DEFAULT from '@salesforce/label/c.INF_DISPLAY_ON_DEFAULT';
import INF_DISPLAY_REPORT_DISPLAY from '@salesforce/label/c.INF_DISPLAY_REPORT_DISPLAY';
import INF_EXPAND_REPORT_ROWS from '@salesforce/label/c.INF_EXPAND_REPORT_ROWS';
import INF_DEFAULT_ROUNDING from '@salesforce/label/c.INF_DEFAULT_ROUNDING';

export default {
    INF_DUPLICATE_ACCOUNTING_PERIOD_MSG: INF_DUPLICATE_ACCOUNTING_PERIOD_MSG,
    INF_DUPLICATE_NAME_LOGO_MSG: INF_DUPLICATE_NAME_LOGO_MSG,
    INF_EXPAND_REPORT_ROWS_MSG: INF_EXPAND_REPORT_ROWS_MSG,
    INF_ROUNDING_HELP: INF_ROUNDING_HELP,
    ERR_VALUE_REQ_SAVE_SETTINGS: ERR_VALUE_REQ_SAVE_SETTINGS,
    INF_REPORT_DISPLAY: INF_REPORT_DISPLAY,
    COMMON_SELECT_LEDGER: COMMON_SELECT_LEDGER,
    INF_COMPANY_NAME_LOGO: INF_COMPANY_NAME_LOGO,
    INF_COMPANY_NAME: INF_COMPANY_NAME,
    INF_LOGO: INF_LOGO,
    INF_DIEMENSION_CONSTRAINTS: INF_DIEMENSION_CONSTRAINTS,
    INF_ACTUAL_SIZE_PREVIEW: INF_ACTUAL_SIZE_PREVIEW,
    INF_DUPLICATE_ON_ALL_LEDGERS: INF_DUPLICATE_ON_ALL_LEDGERS,
    INF_COLUMN_HEADER_FOR_PERIOD_NAME: INF_COLUMN_HEADER_FOR_PERIOD_NAME,
    INF_DISPLAY_ON_DEFAULT: INF_DISPLAY_ON_DEFAULT,
    INF_DISPLAY_REPORT_DISPLAY: INF_DISPLAY_REPORT_DISPLAY,
    INF_EXPAND_REPORT_ROWS: INF_EXPAND_REPORT_ROWS,
    INF_DEFAULT_ROUNDING: INF_DEFAULT_ROUNDING
}