import INF_RECORDS_CREATED_SUCCESSFUL from '@salesforce/label/c.INF_RECORDS_CREATED_SUCCESSFUL';
import INF_CREATE_GL_ACCT_DEFAULTS from '@salesforce/label/c.INF_CREATE_GL_ACCT_DEFAULTS';
import INF_TRANSACTIONAL_BUDGET_LEDGERS_ALLOWED from '@salesforce/label/c.INF_TRANSACTIONAL_BUDGET_LEDGERS_ALLOWED';

export default {
    INF_RECORDS_CREATED_SUCCESSFUL: INF_RECORDS_CREATED_SUCCESSFUL,
    INF_CREATE_GL_ACCT_DEFAULTS: INF_CREATE_GL_ACCT_DEFAULTS,
    INF_TRANSACTIONAL_BUDGET_LEDGERS_ALLOWED: INF_TRANSACTIONAL_BUDGET_LEDGERS_ALLOWED
}