import CONVENIENCE_FEES from '@salesforce/label/c.CONVENIENCE_FEES';
import INF_CONVENIENCE_FEES_CHARGED_HELPTEXT from '@salesforce/label/c.INF_CONVENIENCE_FEES_CHARGED_HELPTEXT';

export default {
    CONVENIENCE_FEES : CONVENIENCE_FEES,
    INF_CONVENIENCE_FEES_CHARGED_HELPTEXT : INF_CONVENIENCE_FEES_CHARGED_HELPTEXT
}