import ERR_DURING_LOAD from '@salesforce/label/c.ERR_DURING_LOAD';
import INF_RECONCILIATION_SUCCESSFULLY_COMPLETED from '@salesforce/label/c.INF_RECONCILIATION_SUCCESSFULLY_COMPLETED';
import INF_RECONCILIATION_COMPLETE from '@salesforce/label/c.INF_RECONCILIATION_COMPLETE';
import INF_BANK_REC_CALCULATION_UPDATED_RECONCILIATION_COMPLETED from '@salesforce/label/c.INF_BANK_REC_CALCULATION_UPDATED_RECONCILIATION_COMPLETED';
import INF_RECONCILIATION_IN_PROGRESS from '@salesforce/label/c.INF_RECONCILIATION_IN_PROGRESS';
import INF_BANK_RECONCILIATION_CREATION_IN_PROCESS from '@salesforce/label/c.INF_BANK_RECONCILIATION_CREATION_IN_PROCESS';
import INF_AUTO_CLEAR_JOB_IN_PROGRESS from '@salesforce/label/c.INF_AUTO_CLEAR_JOB_IN_PROGRESS';
import WRN_GL_BALANCE_NOT_CALCULATED_FALLS_IN_ARCHIEVE_PERIOD from '@salesforce/label/c.WRN_GL_BALANCE_NOT_CALCULATED_FALLS_IN_ARCHIEVE_PERIOD';
import INF_RECONCILIATION_CALC_STMT_BALANCE_TO_GL_BALANCE from '@salesforce/label/c.INF_RECONCILIATION_CALC_STMT_BALANCE_TO_GL_BALANCE';
import INF_RECONCILIATION_CALC_GL_BALANCE_TO_STMT_BALANCE from '@salesforce/label/c.INF_RECONCILIATION_CALC_GL_BALANCE_TO_STMT_BALANCE';
import INF_GL_DIFFERENCE from '@salesforce/label/c.INF_GL_DIFFERENCE';
import INF_BT_DATE_POPULATED_AUTO_CLEARED from '@salesforce/label/c.INF_BT_DATE_POPULATED_AUTO_CLEARED';
import INF_RECONCILIATION_CALC_STMT_BALANCE_TO_CALC_BALANCE from '@salesforce/label/c.INF_RECONCILIATION_CALC_STMT_BALANCE_TO_CALC_BALANCE';
import INF_OPERATOR1 from '@salesforce/label/c.INF_OPERATOR1';
import INF_OPERATOR2 from '@salesforce/label/c.INF_OPERATOR2';
import INF_EQUALS_LOWERCASE from '@salesforce/label/c.INF_EQUALS_LOWERCASE';
import INF_VS_LOWERCASE from '@salesforce/label/c.INF_VS_LOWERCASE';
import INF_VS_SPACER from '@salesforce/label/c.INF_VS_SPACER';
import INF_VS from '@salesforce/label/c.INF_VS';

export default {
    ERR_DURING_LOAD: ERR_DURING_LOAD,
    INF_RECONCILIATION_SUCCESSFULLY_COMPLETED: INF_RECONCILIATION_SUCCESSFULLY_COMPLETED,
    INF_RECONCILIATION_COMPLETE: INF_RECONCILIATION_COMPLETE,
    INF_BANK_REC_CALCULATION_UPDATED_RECONCILIATION_COMPLETED: INF_BANK_REC_CALCULATION_UPDATED_RECONCILIATION_COMPLETED,
    INF_RECONCILIATION_IN_PROGRESS: INF_RECONCILIATION_IN_PROGRESS,
    INF_BANK_RECONCILIATION_CREATION_IN_PROCESS: INF_BANK_RECONCILIATION_CREATION_IN_PROCESS,
    INF_AUTO_CLEAR_JOB_IN_PROGRESS: INF_AUTO_CLEAR_JOB_IN_PROGRESS,
    WRN_GL_BALANCE_NOT_CALCULATED_FALLS_IN_ARCHIEVE_PERIOD: WRN_GL_BALANCE_NOT_CALCULATED_FALLS_IN_ARCHIEVE_PERIOD,
    INF_RECONCILIATION_CALC_STMT_BALANCE_TO_GL_BALANCE: INF_RECONCILIATION_CALC_STMT_BALANCE_TO_GL_BALANCE,
    INF_RECONCILIATION_CALC_STMT_BALANCE_TO_CALC_BALANCE: INF_RECONCILIATION_CALC_STMT_BALANCE_TO_CALC_BALANCE,
    INF_RECONCILIATION_CALC_GL_BALANCE_TO_STMT_BALANCE: INF_RECONCILIATION_CALC_GL_BALANCE_TO_STMT_BALANCE,
    INF_GL_DIFFERENCE: INF_GL_DIFFERENCE,
    INF_BT_DATE_POPULATED_AUTO_CLEARED: INF_BT_DATE_POPULATED_AUTO_CLEARED,
    INF_OPERATOR1: INF_OPERATOR1,
    INF_OPERATOR2: INF_OPERATOR2,
    INF_EQUALS_LOWERCASE: INF_EQUALS_LOWERCASE,
    INF_VS_LOWERCASE: INF_VS_LOWERCASE,
    INF_VS_SPACER: INF_VS_SPACER,
    INF_VS: INF_VS
}