import INF_REDEFINE_SEARCH_CRITERIA_TO_RETRIEVE_LESS_RECORDS from '@salesforce/label/c.INF_REDEFINE_SEARCH_CRITERIA_TO_RETRIEVE_LESS_RECORDS';
import INF_RECORDS_OF_SEARCH_DISPLAYED_BELOW from '@salesforce/label/c.INF_RECORDS_OF_SEARCH_DISPLAYED_BELOW';
import INF_THE_FIRST from '@salesforce/label/c.INF_THE_FIRST';
import INF_FOUND_THAT_MATCH_FILTER_CRITERIA from '@salesforce/label/c.INF_FOUND_THAT_MATCH_FILTER_CRITERIA';

export default {
    INF_REDEFINE_SEARCH_CRITERIA_TO_RETRIEVE_LESS_RECORDS: INF_REDEFINE_SEARCH_CRITERIA_TO_RETRIEVE_LESS_RECORDS,
    INF_RECORDS_OF_SEARCH_DISPLAYED_BELOW: INF_RECORDS_OF_SEARCH_DISPLAYED_BELOW,
    INF_THE_FIRST: INF_THE_FIRST,
    INF_FOUND_THAT_MATCH_FILTER_CRITERIA: INF_FOUND_THAT_MATCH_FILTER_CRITERIA
}