import WRN_NOT_ALLOWED_VAT from '@salesforce/label/c.WRN_NOT_ALLOWED_VAT';
import INF_PLEASE_CONTACT_SALES_TEAM from '@salesforce/label/c.INF_PLEASE_CONTACT_SALES_TEAM';
import INF_FOR_FURTHER_INFO from '@salesforce/label/c.INF_FOR_FURTHER_INFO';
import INF_OTHER_TAX_METHODS_FOUND_ON_THIS_NEW from '@salesforce/label/c.INF_OTHER_TAX_METHODS_FOUND_ON_THIS_NEW';
import COMMON_PAGE_LOWERCASE from '@salesforce/label/c.COMMON_PAGE_LOWERCASE';
export default {
    WRN_NOT_ALLOWED_VAT : WRN_NOT_ALLOWED_VAT,
    INF_PLEASE_CONTACT_SALES_TEAM : INF_PLEASE_CONTACT_SALES_TEAM,
    INF_FOR_FURTHER_INFO : INF_FOR_FURTHER_INFO,
    INF_OTHER_TAX_METHODS_FOUND_ON_THIS_NEW : INF_OTHER_TAX_METHODS_FOUND_ON_THIS_NEW,
    COMMON_PAGE_LOWERCASE : COMMON_PAGE_LOWERCASE
}